### ISSUE TITLE
Create Hack Club org on LinkedIn

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#1008]
_From @zachlatta on January 27, 2017 17:53_

Create an organization on LinkedIn for Hack Club so club leaders & members can link to it on their profiles. See https://www.linkedin.com/in/bhargavy for an example of what it looks like without an official organization created.

_Copied from original issue: hackclub/meta#675_

**Comment by MaxWofford** [comment]
@mafia-007: Please don't comment on our issues and PRs with unrelated messages. If you are interested in contributing, check out our [code of conduct](https://conduct.hackclub.com).

You will be blocked if you continue to post disruptive messages.

**Comment by zachlatta** [comment]
Not planning on doing this, closing for the time being.
