### ISSUE TITLE
Front Page Links

### ISSUE THREAD

**Issue by Bush1do** [hackclub/hackclub#1036]
Not sure it's just an issue on my browser but these buttons the Hack Club front page aren't functional on Firefox.

![capture](https://user-images.githubusercontent.com/12645067/29294818-45fe73be-811f-11e7-8551-e8ecdc6aa686.PNG)

**Comment by paked** [comment]
Thanks for pointing this out @Bush1do!

I'm going to move this issue over to it's relevant repository, namely [monolith](https://github.com/hackclub/monolith).

**Comment by paked** [comment]
This issue was moved to hackclub/monolith#108
