### ISSUE TITLE
Update branding of example slideshow presentations in club guide

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#1041]
We currently have two example presentations linked at https://github.com/hackclub/hackclub/tree/master/clubs#slideshow-presentations ([1](https://docs.google.com/presentation/d/1QhErlJS6rnqu78guPBWuJ1SUyPJKLbxzLNuSN9qVw0c/edit#slide=id.p) and [2](https://docs.google.com/presentation/d/1WCerU9JhJY6L5kM7SrIlYcABwxpqcjmxmSRXilvWAaY/edit#slide=id.g833fec56d_2_45)).

If you look at them, you'll see that the background is no longer within our brand. We're no longer using gradients for our logo and colors. Instead we're using the opaque red on our website.

<img width="1552" alt="screen shot 2017-09-04 at 23 35 11" src="https://user-images.githubusercontent.com/992248/30048204-0589b864-91ca-11e7-9b18-4715d356eb55.png">

<img width="1552" alt="screen shot 2017-09-04 at 23 35 16" src="https://user-images.githubusercontent.com/992248/30048218-1480e694-91ca-11e7-9640-d922b4a7c9f0.png">

To resolve this issue, change the formatting of the slides in both presentations to match our current brand. This means the background should be our new red and if tweaks need to be made to keep the presentations looking nice, make them.

**Comment by MaxWofford** [comment]
They're both using the new color scheme.

![screenshot_2017-09-10_21 43 07](https://user-images.githubusercontent.com/5891442/30258819-8a68e9f0-9671-11e7-8437-365e43d89fb3.png)
