### ISSUE TITLE
bulckcah.com loads slow and requests timeout

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#1057]
@cravend found this issue:
https://hackclub.slack.com/archives/C0J7C6YET/p1506428723000264

Right now if I load https://bulckcah.com, the page loads slowly and will timeout before all it's assets are loaded:

![screenshot_2017-09-26_05 29 44](https://user-images.githubusercontent.com/5891442/30860393-d491bf78-a27b-11e7-9da5-0e905cfa3048.png)

This page needs to load fully for people on locked down networks so they'll have access to the content on https://hackclub.com.

**Comment by zachlatta** [comment]
Closed by hackclub/proxy@70782725cbb972adf1c991f378e9f39dd21c4993. I believe this was a result of the server double compressing proxied responses and overwhelming itself.
