### ISSUE TITLE
Create a check-in attendance dashboard

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#1058]
It'd be useful to have a Mode Analytics dashboard with all the check-in attendance data so we can keep track of a club's health over time.

Here's a rough sketch from an in-person meeting with @zachlatta and @paked:

![img_20170926_171150](https://user-images.githubusercontent.com/5891442/30895879-f41b7c40-a301-11e7-8363-c88a138c41d7.jpg)

**Comment by MaxWofford** [comment]
https://modeanalytics.com/hackclub/reports/ef2742373cb6

**Comment by zachlatta** [comment]
![](http://img.guggy.com/media/rkeo52Qt6G/animated/0/h/9rJKhiSHEAHd5sqFpyVrGJb5RLk6ZRwZTeRLQcSmpbZna5rPYPUuMiLQhmptogLs1RT3PfLuXsfHnxsY4y2LJQvvfppkt4meSVGESZ3BN9-AHVTWvDO136r6pZy7whB-0/guggy.gif)
