### ISSUE TITLE
Create dashboard for showing check-in response rate

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#1075]
Per @hackclub/staff's discussion this morning, we'll be working to bring our check-in response rate to 90% by 11/06. As part of this, it's important that we're able to see how we're doing towards this goal.

The actual implementation of this dashboard is up to you, but a few suggestions:

- (Big number) Overall response rate from last check-in cycle
- (Line chart / bar chart) Overall response rate plotted over time
- (Area chart) Response rate plotted over time broken down by Streak assignee (so we can see your response rate vs. @MaxWofford's)
- (Table) Clubs in the current check-in cycle that haven't responded yet, so we can know who we need to follow-up with

**Comment by MaxWofford** [comment]
Going to make a funnel on dashboard with stages along these lines:
![2017-10-18 20 55 31](https://user-images.githubusercontent.com/5891442/31753658-d9c2291a-b446-11e7-81fc-73e700ce271c.png)

**Comment by MaxWofford** [comment]
Just created https://modeanalytics.com/hackclub/reports/bc845377caa2/runs/f07a10f5b97b for this
