### ISSUE TITLE
Replace Pico8 workshop with open source software

### ISSUE THREAD

**Issue by retiform** [hackclub/hackclub#1151]
Reasons: 
* Clubs probably do not want to spend money on something as trivial as pico8.
* Pico8 source code can not be modified, discourages hacking

Fortunately there are two Pico8 style machines (with one being a clone) that are open source.

The [TIC-80](https://tic.computer/) a pico8 clone that both runs offline and in a browser.  It can also be run on android.  The browser feature would also be useful for clubs on chromeos or school computers.  It supports code in: Lua or Moonscript or JavaScript or Wren or Fennel .  Based on my limited tests of it, it is pretty easy to use. It seems to have very complete documentation.  Probably the best choice for now.

* written in c
* mit licensed

It has a PRO version with more features, where the binaries cost money, but the source code is available for free (with permission to compile it).  The free version is 100% free.

For this one at least, the workshop should mostly just be copy paste to go from pico to TIC-80, given TIC is mostly a pico8 clone with added functionality.

~~ [Unicorn Console](https://github.com/Gigoteur/UnicornConsole)~~
~~Very early in development.  I would put this as one to watch.~~ EDIT: Definitely dead, semi functional.
Features: webassembly version (though it does not seem to host it anywhere), also supports android.~~
* more colors than TIC-80~~
* Supports code through rust, python, or Lua
* Has somewhat worse documentation.
* written in rust
* no pro version, but I believe all  versions need to be compiled.  Either way, a problem hack club could solve.
* mit licensed

**Comment by zachlatta** [comment]
Thoughts @jajoosam?

**Comment by retiform** [comment]
Im happy to do the work on getting the Pico8 workshop to work on TIC-80

**Comment by jajoosam** [comment]
I tried TIC-80 a while ago, but preferred pico8 because it was much easier to start of with, all the editors existed - sound, map, and music.

Also, the pico8 community is super active - there's an established ecosystem for sharing hugs and solutions.

I'm pretty sure we'll be able to work something out that lets us licensed pico8 for free - I wrote an email to zero (the maker), and he gave me free licences for my whole club :)

**Comment by zachlatta** [comment]
Can you see if they could give licenses to all of Hack Club?

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )

**Comment by retiform** [comment]
> preferred pico8 because it was much easier to start of with, all the editors existed - sound, map, and music.

@jajoosam what do you mean by that?  TIC-80 comes with support for that by default.  Was this not the case when you tried it?

**Comment by jajoosam** [comment]
> TIC-80 comes with support for that by default. Was this not the case when you tried it, or do you mean pico8 does it better in some way?


@retiform - TIC-80 didn't have all the editors when I tried it, as far as I remember. I'll try to give it another try soon :)

**Comment by retiform** [comment]
Status on this?

**Comment by jajoosam** [comment]
Oops, forgot about this.

I'll try it out this week and send an update

**Comment by retiform** [comment]
Note: there is the nico 8 console + a workshop on https://codingworkshops.org/

**Comment by retiform** [comment]
Tried out TIC-80 with my club yesterday.  They loved it.

**Comment by jajoosam** [comment]
@retiform that's super cool! did you write a workshop on tic-80 for your club?

**Comment by retiform** [comment]
@jajoosam I have not written one for my club, though I probably could. We were kind of just testing it out.

**Comment by lachlanjc** [comment]
Closing for now. Would still love to do this in the future :)
