### ISSUE TITLE
Decide future of Slack workshop

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/hackclub#1154]
As Mingjie pointed out, our Slack workshop is desperately out of date. I'm fine with entirely axing it & adding a redirect to our new Slack page, which I think explains our Slack pretty well. We could also rewrite it with new content. Thoughts on this @MaxWofford?

**Comment by MaxWofford** [comment]
I think the current Slack flow is pretty good. Let's remove the workshop. If people are confused we can make a new one

**Comment by MaxWofford** [comment]
Why not move it to the retired workshop section?

**Comment by lachlanjc** [comment]
I’d rather have Retired be “we’re not updating this anymore” vs “this is actively wrong”. Is there a scenario where the old workshop is helpful? Our Git history is public (with commit search).

**Comment by MaxWofford** [comment]
Yeah, I agree with that. I'll delete the Slack workshop & update the index numbers

**Comment by lachlanjc** [comment]
Awesome, appreciated!

**Comment by zachlatta** [comment]
👍 to all

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )
