### ISSUE TITLE
Platformer workshop missing link to p5.play.js

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/hackclub#1158]
4 separate people have been unable to run Platformer today before I discovered it no longer has the necessary p5.play.js link.

**Comment by zachlatta** [comment]
👏👏👏

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )
