### ISSUE TITLE
Add note to ignore most editor errors

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/hackclub#1159]
This one is hard. But everyone at my club who has done Dodge, Platformer, or the other workshops involving linking JS via a script tag ask why there’s an error next to most of their lines in replit/Glitch (saying p5 objects, etc are undefined, because p5 is linked from HTML). I hesitate to say “ignore all the errors” because it feels wrong, but that’s what they need to do. Adding some kind of note would be helpful there. Better yet, if there’s any way to solve this (without Webpack).

**Comment by zachlatta** [comment]
👍👍👍

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by polytroper** [comment]
Opened the final code for dodge in repl.it. I don't see any errors; think they fixed this?

**Comment by lachlanjc** [comment]
Yep, that's awesome!
