### ISSUE TITLE
Workshops use index.css, repl.it uses style.css

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#1163]
The starter workshops assume this:
![index_css-8b65e5a052a2256ab295dfb7883ca00d-b9b2f](https://user-images.githubusercontent.com/5891442/48374826-d3e1f680-e67a-11e8-9d81-99be13e66021.png)
but repl.it's default file names are:
![screenshot 2018-11-12 13 00 35](https://user-images.githubusercontent.com/5891442/48374893-f6740f80-e67a-11e8-93af-56d89bf27ed1.png)

**Comment by MaxWofford** [comment]
cc @yevbar

**Comment by dinaelhanan** [comment]
Tried fixing this #1164!

**Comment by MaxWofford** [comment]
Reopening because outdated filenames are still used in some workshops (context: https://github.com/hackclub/hackclub/pull/1164#issuecomment-439942303)

**Comment by MaxWofford** [comment]
@dinaelhanan: The instances to fix are in the starter track:

<img width="1155" alt="screenshot 2018-11-19 18 38 47" src="https://user-images.githubusercontent.com/5891442/48748064-63af1400-ec2a-11e8-9460-1ac2e1199182.png">

You can search for `index.css` in those workshops and still find them:

<img width="1117" alt="screenshot 2018-11-19 18 39 29" src="https://user-images.githubusercontent.com/5891442/48748098-85a89680-ec2a-11e8-8e6e-556ffc89ec2d.png">

**Comment by dinaelhanan** [comment]
ok I'll work on those 👍
