### ISSUE TITLE
Create “best coding tools” workshop

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/hackclub#1170]
According to Moz, this is a popular query. Could make an interesting “workshop”:

- Editors/IDEs (VSCode, Atom, Xcode, etc)
- Frameworks (Gatsby, Next, Express, Rails)
- Browser console
- Terminal apps (Hyper, iTerm 2)

**Comment by zachlatta** [comment]
Great! Want to take point on writing this?

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )
