### ISSUE TITLE
Adding information about Netlify to Workshops (blog?)

### ISSUE THREAD

**Issue by itsmingjie** [hackclub/hackclub#1181]
I was recently asked by members where they can host their own blogs. Although for static websites and some static generators, GitHub pages already have most of the functionalities that one needs, I still think that Netlify is such an awesome tool that's also quite beginner friendly. Also, the current [GitHub Pages](https://hackclub.com/workshops/github_pages) workshop is outdated with information from back when we were still in C9.

There should be a beginner-friendly guide by Hack Club for beginners to host a continuously deployed website to Netlify (or other equally great platforms). It doesn't have to be an explicit guide on how to use Netlify. It can be included in a workshop like "how to create your own blog", etc. It should include information like how to hook up your own domain to the hosting service, as well as how to use some of the relatively more advanced features like branch deploying, or build previews.

**Comment by MaxWofford** [comment]
cc @polytroper

**Comment by polytroper** [comment]
Hmm. I agree that a netlify workshop would be cool, but TBH I think the best course of action is just to update the GitHub Pages workshop. If the goal is just to get people up and running with a simple site, it's really hard to beat the simplicity of Pages. But maybe I am just showing my bias because I use pages for everything ^_^

**Comment by polytroper** [comment]
Looking at the pages workshop and comparing to https://pages.github.com/

This is where we run into a fundamental tension with Hack Club workshops: ideally we want people to have a friendly, approachable experience with our workshops. However, github has already built something much better than we built or will build.

I kinda want to say that the "Host a blog on GitHub pages" workshop should be a brief description of what pages can do for you, followed by a big fat hyperlink to the official Pages landing page.

**Comment by itsmingjie** [comment]
@polytroper The blogging part also needs to be explained in a more detailed way - we currently don't have anything like that, and we should definitely get things like Jekyll & Hugo & all these static site generators out there before people start writing blogs with vanilla JavaScript showing and hiding elements on the same `index.html` page 😅 (seen it).

**Comment by lachlanjc** [comment]
@polytroper Let's make this issue clearly actionable with whatever next steps are here
