### ISSUE TITLE
Deprecate Cloud9 workshops

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/hackclub#1188]
We're deprecating our Cloud9 integration, but a number of non-retired workshops still mention it.

- find_bigfoot
- notes_to_self
- rails_notes
- ajar
- todo_app_using_meanjs
- chat
- I probably missed some

We need to decide what we're going to do with these—update them? deprecate them? etc.

**Comment by polytroper** [comment]
Deprecate for now. In a perfect world I'd find a community member to update. If anyone has ideas for who may be appropriate for that, plz recommend

**Comment by MaxWofford** [comment]
@polytroper can you take point on deprecating them?

**Comment by polytroper** [comment]
on it
