### ISSUE TITLE
Add individual authors to all workshops

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/hackclub#1190]
I'm rolling out authors on the /workshops page soon. @polytroper, could you find out who created the starter workshops & put in the usernames?

**Comment by MatthewStanciu** [comment]
Closing this if it's okay. Every workshop appears to have an author.

**Comment by lachlanjc** [comment]
Kind of. If we know who originally wrote the ones we stubbed with “Hack Club staff,” would be great to fill in, otherwise I’ll add support to the new site for when there’s no usernames.

**Comment by MatthewStanciu** [comment]
Which ones were written by “Hack Club Staff” other than the one about starting your club?

**Comment by lachlanjc** [comment]
You’re right, looks like this is mostly fixed.

**Comment by MatthewStanciu** [comment]
(The workshop about starting your own Hack Club will probably be removed anyway, so)

**Comment by lachlanjc** [comment]
Please do!!
