### ISSUE TITLE
Fix workshop table of contents link scroll when rehacks gallery is open

### ISSUE THREAD

**Issue by alfphaderp** [hackclub/hackclub#1191]
In workshop pages like https://hackclub.com/workshops/personal_website, if the rehacks gallery is fully expanded after clicking "Show All" when links in the table of contents are clicked, the page does not scroll all the way to the desired section.

**Comment by lachlanjc** [comment]
I’m not able to replicate this issue on iOS Safari. What browser are you using?

**Comment by MaxWofford** [comment]
Able to replicate w/ macOS Safari

**Comment by alfphaderp** [comment]
I was using Chrome on Windows 10. I was also able to replicate it on iOS Safari however.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lachlanjc** [comment]
@polytroper They’re just using regular HTML ID permalinks on headings. Which is why this bug is so confusing—that’s standard browser functionality. The one thing I can think of is if the carousel projects have IDs in the DOM that are overriding the headings later on the page.

**Comment by polytroper** [comment]
If that were the case it would likely be more consistent across browsers,
no?

**Comment by lachlanjc** [comment]
Yep. This issue is happening on Personal Website, not on some other workshops though (?)

**Comment by alfphaderp** [comment]
I observed this issue on Synth.js as well. The amount of scroll needed to actually reach the target seems to be proportional with how many rows the gallery has.

**Comment by lachlanjc** [comment]
Closing since rehacks has been removed entirely
