### ISSUE TITLE
Twilio coupon code "HackClubRocks" has expired

### ISSUE THREAD

**Issue by tho-cograph** [hackclub/hackclub#1226]
Dear HackClub,
Twilio coupon code "HackClubRocks" has expired. Would anyone have the new one?
Thank you so much.

**Comment by MaxWofford** [comment]
I regret to say we've stopped maintaining the Twilio workshop to focus on other workshops that didn't require signup codes. It was a bunch of effort maintaining the codes and keeping our workshop up to date.

cc @polytroper (anything to add?)
