### ISSUE TITLE
Consistent-ize #ship instructions

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/hackclub#1254]
A [small, random assortment](https://github.com/hackclub/hackclub/search?l=Markdown&q=ship) of workshops end in some kind of call to put creations in #ship. Should probably be on every workshop in the Start category, always have a link to sign up for Slack, & make sure instructions are clear for newcomers.

**Comment by MatthewStanciu** [comment]
Sounds great. I’ll make sure to include this in the upcoming rewrite.

**Comment by MatthewStanciu** [comment]
Closing for now because I don't really know how to proceed and don't feel it's super necessary now that #ship has a new problem (too many people shipping, most are low quality, don't get a lot of engagement). But feel free to reopen if you want it to happen
