### ISSUE TITLE
Help Center requires account

### ISSUE THREAD

**Issue by hkatzdev** [hackclub/hackclub#1267]
The Help Center is currently requiring an account for some reason. An account is free to make, but I believe that an account didn't use to be necessary. The information is not sensitive, and I am not sure when this change was made or if it was intentional.

![Locked Image](https://user-images.githubusercontent.com/44281159/80558459-4fc72000-898f-11ea-9fa0-61e061c83db2.png)

**Comment by tmb** [comment]
yeah—we’re going to move all of our content off of there at some point. sorry for the issues :(

**Comment by MatthewStanciu** [comment]
Any updates here @tmb? I completely forgot about this

**Comment by lachlanjc** [comment]
I did half of this project a few weeks ago, exporting the clubs content, writing a web scraper to convert to MDX, & making a new site with Gatsby Themes. Once Scrapbook stuff is paused, will finish importing content & polishing site, then @itsmingjie is going to do some reorganization on content. Consider it in-progress.

**Comment by itsmingjie** [comment]
@lachlanjc tagging myself in so I know this issue still exists. let me know what you need my help with

**Comment by lachlanjc** [comment]
Yup, it's on the schedule for sometime in the next month. I have a pretty clear plan, but needs a solid day or two of technical work, & even just the import is fairly involved. Definitely happening, most likely pre-school, but not super sure when.

**Comment by maxwofford** [comment]
Think this was closed by #1646
