### ISSUE TITLE
Switch Next.js Dashboard to use alternative weather API

### ISSUE THREAD

**Issue by TheOnlyGhostwolf** [hackclub/hackclub#1273]
Hello!

[In this workshop, called "React - Dashboard with Next.js"](https://workshops.hackclub.com/nextjs_dashboard/), Dark Sky API, which is used here, doesn't accept new registrations anymore. 

![A very cool screenshot](https://user-images.githubusercontent.com/31188082/85778683-7e613d00-b72b-11ea-9a98-3a6cb0ad575e.png)

In another workshop ([Web Development - Dashboard](https://workshops.hackclub.com/dashboard/)), another API is being used - https://openweathermap.org/, which works, so wouldn't it be better if the content of the Next.js dashboard workshop would be updated and OpenWeather API would be used instead? Thanks!

**Comment by lachlanjc** [comment]
Absolutely, this needs to happen, thanks. We’d love a PR if you’re interested!

**Comment by TheOnlyGhostwolf** [comment]
Hello @lachlanjc! 

Will everything be ok if I removed [line 168](https://github.com/hackclub/hackclub/blob/main/workshops/nextjs_dashboard/README.md#L168) from the workshop as the API doesn't provide any short summary for the upcoming days?

**Comment by MatthewStanciu** [comment]
This was also an issue on https://workshops.hackclub.com/dashboard/, but @garrett-lane opened a PR (#1269) a few weeks back to change the API to OpenWeather instead of Dark Sky. It would be super cool if we could use OpenWeather for this workshop too 🙌

**Comment by alchzh** [comment]
the NewsAPI part of the workshop is borked as well because newsapi won't let CORS request with origin other than localhost. Could fix by using a custom CORS anywhere proxy to strip/edit headers, but newsapi probably wouldn't be happy with us publicizing that.

**Comment by me-sachin** [comment]
🎉
