### ISSUE TITLE
Minor code typo in Splatter Paint workshop

### ISSUE THREAD

**Issue by jegfish** [hackclub/hackclub#1274]
In the [Getting Started section](https://workshops.hackclub.com/splatter_paint/#getting-started) of the Splatter Paint workshop, there is a small typo where the large code block says `src="/script.js"`, while the specific code block in the numbered list explaining the code says `src="script.js"`. The only difference is the `/`. Both the path with the slash and the path without it work because on the default repl.it HTML/CSS/JS project script.js is both in the root folder (path with `/`) and in the same folder as the HTML page (path without `/`). I don't know which path is the more correct one, but I lean towards `src="script.js"` because I feel I've seen it more often.

I am happy to make the small change and open a pull request, I'm just following the contribution instructions from README.md because I am a first time contributor and rusty with git.

**Comment by MatthewStanciu** [comment]
Thanks so much for flagging! I just fixed this ✨ https://github.com/hackclub/hackclub/commit/36c9382f9ef3df38b8b1616dfbb9f8d9be10ad42
