### ISSUE TITLE
Error in GitHub actions workflow

### ISSUE THREAD

**Issue by quackduck** [hackclub/hackclub#1518]
For example, in https://github.com/hackclub/hackclub/runs/1557030909
```
Error:  workshops/popup_chrome_extension/index.html: SyntaxError: Unexpected closing tag "body". It may happen when the tag has already been closed by another tag. For more info see w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (82:1)
Error:    80 | 
Error:    81 |     
Error:  > 82 | </body>
Error:       | ^^^^^^^
Error:    83 | 
Error:    84 | </html>
Error:    85 | 
```

I dug around in the specified file ([workshops/popup_chrome_extension/index.html](https://github.com/hackclub/hackclub/blob/main/workshops/popup_chrome_extension/index.html)) but couldn't find anything wrong.

**Comment by quackduck** [comment]
Still an error (this time from `diff`):
```
  Except... Let's actually test the application. Send the URL from above to some friends and then PARTY!
- 
+
 ![Dumbledore and Snape partying](cloud-pq5lbfiab.vercel.app/3dumbledoreparty.gif)
 
 ## What's next?
Error: Process completed with exit code 1.
```

Maybe this is because `diff` took too long? It certainly has a lot of output.

**Comment by sampoder** [comment]
AHHHH I’m going to leave it for now, and just hope it’s the diff

**Comment by sampoder** [comment]
https://github.com/hackclub/hackclub/commit/2eb39c4ebe973b4b3e73a06084586f07d7ca58bb -> Made a temporary fix in this commit

@Matt-Gleich could you please help out with this?

**Comment by quackduck** [comment]
A green tick after so long lol

**Comment by Matt-Gleich** [comment]
hmm this is weird. Taking a look now.

**Comment by sampoder** [comment]
thanks Matt!

**Comment by Matt-Gleich** [comment]
np! I am working on a fix right now where we just have prettier ignore that folder.

**Comment by Matt-Gleich** [comment]
I'll make a PR soon and link it to this issue
