### ISSUE TITLE
Workshop Bounty Program: Completing the Mission

### ISSUE THREAD

**Issue by sampoder** [hackclub/hackclub#1597]
The Workshop Bounty program has ended. The ending set up is as follows:

**If at midnight on December 31st you have an open PR:** your workshop will be reviewed until it is (in most cases) merged or there is an issue identified that means it simply can’t be merged (very rare).

**If in the timeframe from December 21st to the 31st you’ve had a PR closed:** You are required to make a resubmission of that same workshop before Jan 10. Your workshop will be reviewed until it is (in most cases) merged or there is an issue identified that means it simply can’t be merged (very rare).

**If you have had a PR closed before December 21st or submit a workshop for the first time after midnight on December 31st:** it will not be reviewed. 

---

For convenience reasons, here is a list of PRs that are valid. A purple circle represents a workshop that needs a review from the "workshop god" or @MatthewStanciu.

**Valid PRs Awaiting Review:**

None.

**Valid PRs Awaiting Resubmission:**

Once your PR has been reviewed, we ask that you submit a revision with 10 days. If you don't we can't guarantee that the PR will still be eligible. We're willing to providing extensions, just let us (@sampoder, @faisalsayed10 or @MatthewStanciu) know in advance.

- Minecraft Modding Workshop by @KaiDevrim
- Mad Libs Workshop by @JakeGerber 
- Shapes Drawing Program by @JakeGerber 
- Expense Tracker by @iamsid47
- Facial Expression/Emotion Detector by @iamsid47 
- Sudoku Workshop by @JakeGerber 
- Spacebar Game by @JakeGerber  
- Fibonacci Sequence Generator by @iamsid47 
- Flappy Learning by @ImBIOS  
- Meme generator workshop by @aaryanporwal  
- 3D Heatmap Workshop by @shivesh01
- Breakfast_plate is created by @Sid672
- Workshop on Hosting and Custom Domains by @aaryanporwal  

---

The above list will be regularly updated. If you see something that needs changing, or believe that a PR that should be there is missing then please raise it in a comment on this issue. 

The Workshop Bounty review team is small so please remain patient. 

Thanks,

@sampoder 🚀

**Comment by faisalsayed10** [comment]
Rock paper scissors in python was closed because there is already a workshop on that ^

**Comment by sampoder** [comment]
Noted, removed.

**Comment by sampoder** [comment]
**Important update:** Once your PR has been reviewed, we ask that you submit a revision with 10 days. If you don't we can't guarantee that the PR will still be eligible. We're willing to providing extensions, just let us know in advance :D

**Comment by cfanoulis** [comment]
rust game workshop has been re-submitted as #1617

**Comment by KhushrajRathod** [comment]
Kuizzy workshop was re-submitted yesterday as https://github.com/hackclub/hackclub/pull/1626

**Comment by faisalsayed10** [comment]
Just updated this

**Comment by iamsid47** [comment]
Hey! Can you please remove 

1. Comp interest calc
2. Random and a strong password generator using Python
3. Contactless Temperature Meter

Won't be submitting these workshops.

**Comment by sampoder** [comment]
We did it team! Our job is now so I'm closing.

Thank you all <3
