### ISSUE TITLE
Joining Request

### ISSUE THREAD

**Issue by Kushal997-das** [hackclub/hackclub#1712]
How to join this `hackclub` this organization?

**Comment by sampoder** [comment]
hey! check the readme for instructions :)

**Comment by Kushal997-das** [comment]
> hey! check the readme for instructions :)

@sampoder could you please tell me how may i join join i checked the `readme.md` file but unable to understand this that is why i created a issue here. I hope you understand .

**Comment by sampoder** [comment]
![Uploading Screenshot 2021-03-01 at 12.23.55 AM.png…]()

**Comment by sampoder** [comment]
<img width="619" alt="Screenshot 2021-03-01 at 12 24 06 AM" src="https://user-images.githubusercontent.com/39828164/109425690-70835a80-7a24-11eb-967e-04a5d87a0000.png">
