### ISSUE TITLE
Let me join into organization

### ISSUE THREAD

**Issue by thuongtruong1009** [hackclub/hackclub#1745]
Hi guys!
My name is Tran Nguyen Thuong Truong - thuongtruong1009
I come from VietNam with open-source code love.
My Github link: https://github.com/thuongtruong1009
I would like to join your organization to learn more and more.
Thank you very much!

**Comment by sampoder** [comment]
Cowabunga! A wild hacker I see 👁️ 👁️ 

Let me guide you in the direction of https://hack.af/draw-dino....

Safe travels!
