### ISSUE TITLE
kahoot.js-updated is no longer maintained

### ISSUE THREAD

**Issue by YodaLightsabr** [hackclub/hackclub#1781]
While I was doing the Hacking Kahoot I ran into some errors with kahoot.js-updated, and I found out that it's deprecated on NPM with the message `kahoot.js-updated is no longer maintained`.

I've been exploring different Kahoot APIs and I haven't yet found any working alternatives.

**Comment by sampoder** [comment]
What errors are you getting?

**Comment by sampoder** [comment]
interesting, could you send me through the code and the package.json your using? I've still managed to get it working

**Comment by YodaLightsabr** [comment]
Oh I see. Replit kept bumping the version of kahoot.js-updated up to `^3.404.1`. I wonder if there's a way around the packager doing that.

**Comment by YodaLightsabr** [comment]
Now I'm getting a different error that I don't understand. https://replit.com/@YodaCode/kahoot.js-updated-test

**Comment by sampoder** [comment]
<img width="1046" alt="Screenshot 2022-05-29 at 12 28 13 AM" src="https://user-images.githubusercontent.com/39828164/170834174-962ab006-2fa5-46b6-a3e8-7547f2669697.png">

**Comment by YodaLightsabr** [comment]
Oops. https://replit.com/@YodaCode/kahootjs-updated-test

**Comment by sampoder** [comment]
The error is caused by an invalid Kahoot Challenge code, I used a valid one and it worked

**Comment by YodaLightsabr** [comment]
Odd. I guess I'll close this. Maybe we could consider forking it and releasing 1 package version in case people wanted to replicate it without the template?
