### ISSUE TITLE
Change colors on link-tree repo to Hack Club Colors 

### ISSUE THREAD

**Issue by abbyfischler** [hackclub/hackclub#1795]
Change the CSS on the link tree website and of the buttons to make the website more Hack Club looking.

Link to link-tree repo: https://github.com/hackclub/link-tree

Hack Club's branding guide can be found here: [hackclub.com/brand](https://hackclub.com/brand/)

**Comment by sampoder** [comment]
Let's transfer this to the link-tree repo. Or transfer the base link-tree repo into the Hack Club account. Happy to help with this through Slack.
