### ISSUE TITLE
Want to join the HackClub

### ISSUE THREAD

**Issue by ParadoxElder** [hackclub/hackclub#1797]
Hi guys!
My name is David Gavilanez - ParadoxElder
I come from Ecuador with open-source code love.
My Github link: https://github.com/HarmonySkull
I would like to join your organization to learn more and Grow.
Thank you very much!

**Comment by exu3** [comment]
Hi David,

You can join the Hack Club GitHub org by drawing a dinosaur: hack.af/draw-dino. Have fun!

**Comment by wollygfx** [comment]
Hola David,

¡Me da gusto ver a otro hack clubber de Sur América!, espero podamos tener una conversación algún día en el Slack de Hack Club. Te espero ahi, encuentrame como @carlosdafarmer ;)
