### ISSUE TITLE
Addition to the HackClub Github organization

### ISSUE THREAD

**Issue by markrosenbaum** [hackclub/hackclub#1849]
Hi,
I'd like to be added to the HackClub Github organization.  
I am Mark Rosenbaum on the  HackClub Slack.
Thanks,
Mark

**Comment by Hrushal-Nikhare** [comment]
hello there use https://hack.af/draw-dino to draw a dino and you will be added to the organization

**Comment by markrosenbaum** [comment]
Cool, thanks for the help
