### ISSUE TITLE
Remote Control Workshop: Add a tutorial for finding an mp3

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#235]
Add a tutorial to find already hosted mp3 files online. Many people from the MHacks workshop asked us how to do this.

I've found the that the website https://mp3skull.is/ is a pretty decent place to get hosted mp3 files, however, the easiest way to get it is not intuitive:

- Search for a song
- Play the song in mp3 skull
- Inspect element on the player
- Extract the source URL of the mp3 file

See ![](https://s3.amazonaws.com/f.cl.ly/items/0V2u0n2H2d100c083007/Screen%20Recording%202015-09-20%20at%2009.17%20PM.gif)

**Comment by jonleung** [comment]
\cc @paked @Bogidon

**Comment by Bogidon** [comment]
Lol, get them to use http://chehacks.com/music. I made it for my CS Club because mp3skull is blocked on our school network – and I'm sure it's blocked in other places too. CHE Hacks isn't the best solution though. Maybe we can make a git repo with some copyright-free tones?

**Comment by MaxWofford** [comment]
This issue seems inactive so I'll close it for now. If anyone would like to pick it up, feel free to reopen!
