### ISSUE TITLE
Remote Control Workshop: Create wave wand for sound tutorial

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#236]
Many people want to trigger a sound when the wand is waved. On iOS there's some trickiness to this because sounds can only be played in javascript after they have been played once with a mouse click. See [Apple's documentation](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html).

Here is an example of how it would need to work:

```js
var audio = new Audio("http://www.sounddogs.com/previews/4035/mp3/186561_SOUNDDOGS__we.mp3");

document.getElementById("play-button").onclick = function() {
  audio.play();
}

Wand.threshold = 5;
Wand.onWave = function() {
  audio.play();
};
```

Here is the working [JS Bin](http://jsbin.com/fawuda/66/edit?html,css,js,console)

**Comment by jonleung** [comment]
\cc @paked

**Comment by Bogidon** [comment]
Coincidently this was a problem with a hack I made at PennApps VIII (webn.es). I can look into it.

**Comment by jonleung** [comment]
Closing this issue because I'm not sure how high leverage doing this would be.
