### ISSUE TITLE
Remote Control Workshop: More clearly link to JS Bin

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#240]
Here was some feedback we got: "I wish the link to jsbin was more obvious."

Some of the links to JS Bin are not obvious. Perhaps we should turn them into links that look like buttons using images.

**Comment by zachlatta** [comment]
Can you give an example of one of the links that isn't obvious? I'd be
really hesitant to use image buttons as links, for the sake of keeping
things simple.

On Sun, Sep 20, 2015 at 9:46 PM, Jonathan Leung <notifications@github.com>
wrote:

> Here was some feedback we got: "I wish the link to jsbin was more obvious."
>
> Some of the links to JS Bin are not obvious. Perhaps we should turn them
> into links that look like buttons using images.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/240>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
Closing this for the time being because it is inactive and the feedback has not been repeated.
