### ISSUE TITLE
Write guide for setting up a Cloud9 workspace for contribution

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#242]
During the introductory Labs calls we set everyone up with Cloud9 workspaces for making contributions to this repository and refer to the workspaces in `CONTRIBUTING.md`.

As mentioned in #196, create a written guide on setting up a Cloud9 workspace for contribution so non-labs clubs can create that workspace as well.

**Comment by jonleung** [comment]
@zachlatta do you think we should still do this?

\cc @MaxWofford

**Comment by MaxWofford** [comment]
@jonleung Because this will be addressed by https://github.com/hackclub/hackclub/issues/512, I think we should still track the issue

**Comment by jonleung** [comment]
:+1:

**Comment by paked** [comment]
@MaxWofford @jonleung #512 has been closed, however does not really fulfil the goals of this issue.

In the meantime though we have had a [Git and Github (https://github.com/hackclub/hackclub/blob/master/git_and_github) workshop merged into master. Perhaps this closes the issue?

**Comment by MaxWofford** [comment]
@paked Agreed
