### ISSUE TITLE
Ship Maze Workshop

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#339]
This will likely be another p5.js workshop

**Comment by paked** [comment]
Should we look at doing another web development workshop now? I wouldn't
want to oversaturate with games...

**Comment by jonleung** [comment]
@paked that sounds like a good idea but am not currently sure. Any ideas that you have?

**Comment by zachlatta** [comment]
I think another web development workshop would be a good call. Perhaps
doing more stuff with CSS (maybe like introducing Bootstrap/Foundation)?

On Fri, Oct 16, 2015 at 8:25 AM, Jonathan Leung <notifications@github.com>
wrote:

> @paked <https://github.com/paked> that sounds like a good idea but am not
> currently sure. Any ideas that you have?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/339#issuecomment-148745973>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by paked** [comment]
Sure. Bootstrap could be interesting...

Anyway we could introduce firebase? Or would that be too complicated.

**Comment by MaxWofford** [comment]
@paked Firebase workshop could be cool! There are a few examples in hackedu/hack-camp

**Comment by paked** [comment]
Awesome. You see, I'm not convinced people will be engaged with just
bootstrap...

**Comment by zachlatta** [comment]
@paked agreed that Bootstrap alone is not cool enough. I know @jonleung's now planning on making a maze game workshop.

Also, @jonleung, just a quick reminder to communicate to all the leaders that this workshop exists once you've gotten it merged in!

**Comment by jonleung** [comment]
Thanks @zachlatta

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by jonleung** [comment]
Closed by #482
