### ISSUE TITLE
Remote Control Workshop: Add a note that playing some mp3 files works and others don't...

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#355]
`Twilio.callAndPlay` works for playing some mp3s but not others. I havn't been able to figure out which ones work and which ones don't.

We should just leave a note in the workshop that includes:

- Twilio doesn't like playing some mp3
- Here is a list of links to mp3s that we know work

**Comment by MaxWofford** [comment]
When running this workshop in @alexb's high school it seems that whenever hackers ran into a problem like this they would just  keep trying it with different mp3s. Closing this because this isn't a hard fix for hackers in our clubs. If anyone wants to add the note, feel free to reopen this issue!
