### ISSUE TITLE
Create workshop guidelines

### ISSUE THREAD

**Issue by ad510** [hackclub/hackclub#374]
Create guidelines for people who want to write and submit their own workshops to HackEDU.

**Comment by ad510** [comment]
Also, there's a ton of good tutorials online for people to learn anything related to programming, web development, etc. If I contribute a workshop, one thing I'd like to understand better is what the HackEDU workshops do differently that prevents us from just linking to the best existing online tutorials. Also, even though we do make the key workshops ourselves it might be a good idea to collect links to interesting tutorials/articles elsewhere on the Internet (I can probably find some good ones).

**Comment by jonleung** [comment]
Hey @ad510!

The guidelines are [currently being developed here]. @Bogidon is leading the charge on this one right now! Will keep you posted when we get this document to the point where we move it to GitHub!

**Comment by jonleung** [comment]
@ad510 

Re:

> it might be a good idea to collect links to interesting tutorials/articles elsewhere on the Internet (I can probably find some good ones).

Would love your help on that! It might be worthwhile to write a section on "What is different about hackEDU workshops"

**Comment by ad510** [comment]
Thanks for the update. I was chatting with Zach and he suggested making an issue for this. I had previously considered helping more with workshops, but I felt like my teaching style is very different from yours which made it difficult to contribute to the existing workshops. So if I do make workshops they would probably be new ones for the "contrib" folder.

**Comment by zachlatta** [comment]
I was talking with @amiruqdah on Facebook and he's looking to have workshop guidelines created as well before he creates a workshop on building https://github.com/amiruqdah/mario-party (which I think would be super awesome)

**Comment by paked** [comment]
:+1: so hard

**Comment by zachlatta** [comment]
@hackedu/core I'd like to propose prioritizing this.

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by jonleung** [comment]
I'll probably make this after I have made at least 2 workshops follow the same guidelines. Right now only workshop 1 is high enough quality. I need to make workshop 2 as high quality and then I can write guidelines based off of those two workshops.

**Comment by zachlatta** [comment]
:+1:

On Thu, Feb 11, 2016 at 7:55 PM, Jonathan Leung <notifications@github.com>
wrote:

> I'll probably make this after I have made at least 2 workshops follow the
> same guidelines. Right now only workshop 1 is high enough quality. I need
> to make workshop 2 as high quality and then I can write guidelines based
> off of those two workshops.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/374#issuecomment-183170861>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MattHesby** [comment]
Definitely would like to see this happen.  I think a clear guideline and example or two for what constitutes a grade A workshop would really help people feel confident and successful in writing and submitting their own workshops.

**Comment by ad510** [comment]
What the heck. Now that I submitted my first workshop, maybe I'm qualified to write a first draft of this. :smile: Feel free to copy-paste this to somewhere better, and improve it.

## Why workshops?

Before getting into how to make a good workshop, let's start with a more basic question: why run workshops in the first place?

In summer 2015, we ran a series of beginner coding camps, the theory being that if we knew how to run a good summer program, we could take the lessons learned and apply them to running Hack Clubs. At Hack Club, we want to take the hackathon culture of learning how to build your own things, and bring that culture back into schools. So at first we took a hands-off approach, explaining about the growth mindset and encouraging people to do Google searches when they didn't know how to do something.

But that didn't work very well. People basically commented, why were they paying money to learn how to code, only to be told to Google it? Clearly we needed something better. In later summer camp cohorts, we took a more structured approach to teaching. Then we took the lessons we ran in the summer camp and wrote them down as workshops, so that clubs could run these workshops worldwide!

## How are Hack Club workshops different?

So now you might be asking: why do we need to make our own workshops? Why not just point club members to an existing learn-to-code website (which there are many of)?

The answer to that is that we're not just trying to teach people how to code. We're trying to teach people how to become self-learning hackers. It is common for people to finish an online learn-to-code curriculum (or get a full-blown computer science college degree, for that matter), and still not understand why hacking together a project is so *fun*! We want to encourage the kind of mentality where you just randomly decide to code up a project over the weekend (for fun!) and brag about it to friends.

For example, when you're making your own project over the weekend, you don't have a workshop page in front of you telling you how to solve your problem step by step. So in our workshops, we try to teach people step-by-step how to Google things when they're stuck. (Yeah I know, most of the workshops still don't do this. If you want to help improve them, submit a pull request!) Likewise, if there's a bug in your code, you have to know how to debug it by yourself. In other words, we want people to reach the point where they *won't need* workshops to continue the learning process, and this needs a different kind of approach than your typical learn-how-to-code website.

Another issue unique to Hack Club is that many school computers are in a locked-down configuration that prevents students from installing software, such as Chromebooks. We've found that the only solution that works consistently across schools is one where everything can be done through a web browser. This is why we use [Cloud9](https://c9.io) in all of our workshops.

By the way, if you do know about an existing website that meets both of these needs, please tell us on [Slack](https://starthackclub.slack.com/). Making new workshops is a serious bottleneck right now, and it would be so awesome if we didn't have to expend all this effort!

## How do I write an awesome workshop?

To be honest, none of us are experienced workshop writers, so we shouldn't try to pretend to know more than we actually do. :smile:

The best way to write an awesome workshop is to just write a workshop, then test it on friends to find how it can be improved! You will learn much more from doing this than you would ever learn from reading detailed guidelines.

The only strict requirement is that you *must* have club members develop in [Cloud9](https://c9.io) and deploy to [GitHub Pages](https://pages.github.com). See the [Personal Website](https://github.com/hackclub/hackclub/blob/master/workshops/personal_website/README.md) workshop for what the workflow looks like. This is to be consistent with the existing workflow that club members learn, and to play nice with the restrictions that school computers have.

A few more things:

- Try to follow the format and directory structure of existing workshops at https://github.com/hackclub/hackclub/tree/master/workshops/.
- By the end of the workshop, club members should have completed something that they can show their friends.
- We learned from experience that it's best to follow up workshops with extra time for club members to make their project into their own. So try to include some suggestions at the end for how to take the project further!
- Keep in mind that after-school meetings can't go on forever. Try to make your workshop take 1 hour or less to finish.
- Remember that we're Hack Club, not Theoretical Computer Science Club. Try to pick something that doesn't need too much programming knowledge to build, but that looks great when it's done. And try to teach how to learn on your own, such as how to Google things and debug issues in your code.
- If you want to reduce work for maintainers, try to follow this [style guide](https://github.com/hackclub/hackclub/blob/master/GUIDELINES.md#styleguides). But don't worry about it too much, because we will fix formatting issues for you before publishing your workshop.

When you're done, submit a [pull request](https://github.com/hackclub/hackclub/pulls) and we'll take a look at it.

Happy hacking!

**Comment by jkwok91** [comment]
:clap: :clap: @ad510

**Comment by ad510** [comment]
Yeah, and I have an assignment due in 24 hours that I barely started and *really* should be working on, and I procrastinate by doing this instead. I might even have to submit it late at this point. Sigh.

**Comment by zachlatta** [comment]
Woah, this is awesome. Great work @ad510 and I think it'll be an awesome
start for the document itself.

On Fri, Feb 19, 2016 at 12:05 AM, Andrew Downing <notifications@github.com>
wrote:

> Yeah, and I have an assignment due in 24 hours that I barely started and
> *really* should be working on, and I procrastinate by doing this instead.
> I might even have to submit it late at this point. Sigh.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/374#issuecomment-186110672>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by Bogidon** [comment]
WOOOOO. Good job @ad510 

> To be honest, none of us are experienced workshop writers, so we shouldn't try to pretend to know more than we actually do.

I think this is a good way to shipping something out fast. When @paked, @jonleung and I were trying to make the guide we we **super stuck** trying to formalize *every little thing*. :+1:

**Comment by ad510** [comment]
I took some time to revise it after writing the first draft, so it might actually be good enough now to use without additional changes. I would submit a PR except I'm super busy with homework right now, and I feel any PR should reorganize the 3 guidelines/contributing files we currently have.

**Comment by zachlatta** [comment]
Sweet! This is awesome @ad510. I talked with @elishacoad about this and he
said he'd be interested in taking point on submitting a pull request for
this.

/cc @remixz

On Fri, Feb 19, 2016 at 4:03 PM, Andrew Downing <notifications@github.com>
wrote:

> I took some time to revise it after writing the first draft, so it might
> actually be good enough now to use without additional changes. I would
> submit a PR except I'm super busy with homework right now, and I feel any
> PR should reorganize the 3 guidelines/contributing files we currently have.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/374#issuecomment-186460756>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by ad510** [comment]
I'm still very busy with schoolwork, unfortunately. I might have a little time this weekend.

**Comment by ad510** [comment]
Closed by #747
