### ISSUE TITLE
Twilio Workshop: Add explanation for API

### ISSUE THREAD

**Issue by klipspringr** [hackclub/hackclub#411]
Remote Control introduces Twilio's API as a service, but never explicitly states that we're using their API / what an API is.

**Comment by paked** [comment]
@Bogidon Should this go in the "Computer Science Fundamentals" section?

**Comment by jonleung** [comment]
This might be in a vocabulary section?

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by uditdesai** [comment]
The word api in the readme file is a link that goes to a quora page explaining what an api is, I think it would be unnecessary to explain it again when you can easily click the word to find out what it means.

**Comment by jonleung** [comment]
Closing this because @uditdesai believes the status quo to be sufficient. However, this may be clarified further when #239 is completed.

**Comment by jonleung** [comment]
@klipspringr I apologize for completely mishandling this. You brought up a very valid (and helpful) point and I closed the issue without addressing it.

@klipspringr, how do you think we could improve the workshop to bring clarity to the fact that:

- we're using the Twilio API
- what an API is

I'd love the thoughts of others as well.

Thanks again so much for submitting this issue @klipspringr!

**Comment by MaxWofford** [comment]
Reopening because this issue is still being discussed.

**Comment by jonleung** [comment]
Oops, thanks for fixing that @MaxWofford!

Also, closing #239 may help alleviate some of these issues as well.

**Comment by klipspringr** [comment]
Hi @jonleung! Don't even worry about it :-)

I brought up this question mostly because I tend to read quickly, and I didn't see the initial link to the Quora post. Something to consider is that this may not be obvious for people to see. Also, having links, while super great for most people, may not be as accessible for people who are colorblind, visually-impaired, or just straight up don't know understand Github's interface and do not know what a link looks like.

I used this workshop with my students, and none of them opened up the link, or frankly, asked me what an API is. A lot of my students kind of just went with it.

Initially clarifying what an API is by giving the formal definition and saying that this API was built by a company called Twilio would be sufficient, in my opinion.

**Comment by MaxWofford** [comment]
@zachlatta seems to have addressed this with https://github.com/hackclub/hackclub/pull/641. Even though it has the "first-timers-only" tag, I'm going to close this issue for now. @klipspringr If you don't think this properly addresses the issue feel free to reopen!
