### ISSUE TITLE
Look through Bogdan's workshops

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#452]
@Bogidon @JevinSidhu sorry it's taking me so long to get to these!

**Comment by JevinSidhu** [comment]
@jonleung Totally cool man, no worries :100:

**Comment by MaxWofford** [comment]
Just submitted https://github.com/hackclub/hackclub/pull/546 based on this.

**Comment by MaxWofford** [comment]
Just submitted https://github.com/hackclub/hackclub/pull/547 for this.

**Comment by jonleung** [comment]
Updated the scope of this issue because I'll be looking through @JevinSidhu's workshops in #356

**Comment by MaxWofford** [comment]
@jonleung did you mean to link to that issue?

**Comment by jonleung** [comment]
@MaxWofford I fixed the link in my above comment

**Comment by MaxWofford** [comment]
:+1:

**Comment by MaxWofford** [comment]
@jonleung It seems like this is stagnant. Closing for now. If you'd like to reopen, go right ahead!
