### ISSUE TITLE
Workshop folder needs updates.

### ISSUE THREAD

**Issue by saescapa** [hackclub/hackclub#491]
I'l try to send a PR myself, but the Workshop folder in general needs some fixes: Here are some I found:

1. Location: [here](https://github.com/hackedu/hackedu/blob/master/workshops/workshop_details.md#obtaining-a-twilio-account--credentials-20-minutes)
  - Error: ```Follow [the
directions here](twilio/signup.md)``` Does not work.
  - Solution: ```Follow [the
directions here](/lib/twilio-basic/signup.md)```
2. Location: [here](https://github.com/hackedu/hackedu/blob/master/workshops/workshop_details.md)
  - Error Page overall not updated to match new workshops

**Comment by zachlatta** [comment]
Uh oh, some of these errors should be caught by Markcop, right @MaxWofford?

Thank you @saescapa! We'll get on fixing this ASAP.

**Comment by saescapa** [comment]
I'll add more in the comments to keep them organized.

3. Location: [here](http://jsbin.com/fawuda/35/edit?html,js)
  - Error: ```<script type="text/javascript" src="//bit.ly/twilio_client_js"></script>``` Does not work (error given ```ReferenceError: Twilio is not defined```
  - Solution: Replace ```<script type="text/javascript" src="//bit.ly/twilio-basic-with-prompt-v1"></script>```

**Comment by paked** [comment]
Possibly related to #484

**Comment by zachlatta** [comment]
Can you further clarify what you mean by the following? Also, I've submitted #493 to address #1. I'm working on your second comment now.

> 2. Location: [here](https://github.com/hackedu/hackedu/blob/master/workshops/workshop_details.md)
>   - Error Page overall not updated to match new workshops

**Comment by saescapa** [comment]
@zachlatta Sorry, I didn't see your response, what I meant is that there aren't guidelines on how to run other workshops such as Dodge, Soccer or Maze (added recently).

**Comment by zachlatta** [comment]
Ah, gotcha. I'll make another issue to make sure those get created (or we do something different for workshop guidelines).

**Comment by zachlatta** [comment]
Just created #523 to track the facilitation guidelines in a separate issue. Closing this one for now :-).

Thank you so much @saescapa!
