### ISSUE TITLE
It's unclear how to get the output URL in the Portfolio workshp

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#503]
When I was running the portfolio workshop in Estonia, about half of the people doing the workshop asked me how to get the output URL from JS Bin in https://github.com/hackedu/hackedu/tree/master/workshops/portfolio#get-a-link-that-everyone-can-see.

/cc @jonleung

**Comment by jonleung** [comment]
@paked would you actually be interested in working on this at all?

**Comment by paked** [comment]
@jonleung sure. I'm down.

**Comment by jonleung** [comment]
Thanks @paked, want to assign yourself to the issue?
