### ISSUE TITLE
Link back to Dodge sprite explanation in Maze

### ISSUE THREAD

**Issue by paked** [hackclub/hackclub#507]
Currently in the [maze](https://github.com/hackedu/hackedu/tree/master/workshops/maze) workshop, there is not *explanation* for the term "sprite".

Perhaps we should link back to [this section from the dodge workshop](https://github.com/hackedu/hackedu/tree/master/workshops/dodge#some-terminology).

cc: @zachlatta @hellyeah

**Comment by zachlatta** [comment]
I am 100% on board with this. :thumbsup:

On Fri, Nov 20, 2015 at 12:47 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> Currently in the maze
> <https://github.com/hackedu/hackedu/tree/master/workshops/maze> workshop,
> there is not *explanation* for the term "sprite".
>
> Perhaps we should link back to this section from the dodge workshop
> <https://github.com/hackedu/hackedu/tree/master/workshops/dodge#some-terminology>
> .
>
> cc: @zachlatta <https://github.com/zachlatta> @hellyeah
> <https://github.com/hellyeah>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/507>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by paked** [comment]
Closed from #545
