### ISSUE TITLE
Rewrite CONTRIBUTING.md

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#512]
Make it clear how to:

- Fork and manage the repo
- Submit a pull request

Also make sure to update GIFs to say Hack Club instead of hackEDU.

**Comment by sethtrei** [comment]
This would be very helpful.

**Comment by MaxWofford** [comment]
This might close hackclub/hackclub#242

**Comment by paked** [comment]
@zachlatta Looking at your suggestions I'm confused as to why we can't just add those sections. Is a full rewrite completely necessary?

**Comment by paked** [comment]
If so, what kind of structure should we use in order to make sure we do not fall into the same trap.

**Comment by MaxWofford** [comment]
@paked contributors I've worked with usually have trouble because they skip a step or 2 in the `CONTRIBUTING.md`. Perhaps it is too long?

**Comment by paked** [comment]
@MaxWofford can you please permalink that, I can't see a specific step 2

**Comment by MaxWofford** [comment]
@paked I edited my original comment

**Comment by jonleung** [comment]
Just a note: 

I was talking to a club leader who said he would love a workshop / tutorial on how to use GitHub, especially for using pull requests. This club leader worked with @MaxWofford to learn how to submit a pull request and @MaxWofford walked him through  step by step how to submit a pull request. However, he says that it was "super hard" and "I don't remember any of it". I've heard similar things from many others who are learning how to do the pull request process.

**Comment by jonleung** [comment]
Who's taking lead on this issue now? I saw the assignment change of this task to @paked but didn't see too much context. I think it would be helpful for whoever is taking lead on this issue talk to talk with above club leader with the MVP of the new guide to see what's helpful / what's confusing in it.

**Comment by paked** [comment]
@jonleung Looks like I'm the one who will be taking point on this. Could you PM me the name of this leader so I can get in touch and arrange a call.

**Comment by paked** [comment]
I really want to get a solid plan setup for this so we don't have to expend more energy rewriting again in the future.

**Comment by jonleung** [comment]
@paked I really like the work that they've done here: https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst

Give that a look see.

**Comment by jonleung** [comment]
This is also pretty great @paked: https://github.com/atom/atom/blob/master/CONTRIBUTING.md#your-first-code-contribution

**Comment by paked** [comment]
@jonleung Those seem more relevant to the `workshops/CONTRIBUTING.md` file.

**Comment by paked** [comment]
OK. Here are my thoughts on what we can do with `CONTRIBUTING.md`.

Firstly, I think one change that would help tremendously would be to add a table of contents. This would increase the visibility of a *lot* of items, while making a visual pseudo checklist.

I do not think that the [naming conventions](https://github.com/hackclub/hackclub/blob/ae9e2d2aab7ae6f613a94292d6376ae9ef8dd816/CONTRIBUTING.md#naming-conventions) section is that bad, and could perhaps be left as it is.

The [labs](https://github.com/hackclub/hackclub/blob/ae9e2d2aab7ae6f613a94292d6376ae9ef8dd816/CONTRIBUTING.md#labs) section definitely needs to go. It is not relevant (by definition) to all contributors.

**Comment by jonleung** [comment]
> Re:  Could you PM me the name of this leader so I can get in touch and arrange a call.

@paked, I pinged the leader in requestion to see if he's down to talk with us about! I will message you back as soon as he says he's down to talk to us about this! I will also message you their name in the mean time.

**Comment by jonleung** [comment]
@paked and I discussed what changes we want to make going forward. I'm pretty psyched for this `CONTRIBUTING.md`!

**Comment by paked** [comment]
Closed in #574
