### ISSUE TITLE
Link curriculum and attendance spreadsheet via hackclub.io URL

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#516]
_Note that I'm deliberately not linking the attendance and curriculum spreadsheet here so that they are not publicly accessible._

What if we used `attendance.hackclub.io` to link to the curriculum and attendance spreadsheet?

\cc @zachlatta @MaxWofford

**Comment by MaxWofford** [comment]
> Note that I'm deliberately not linking the attendance and curriculum spreadsheet here so that they are not publicly accessible.

> `attendance.hackclub.io`

@jonleung Doesn't including this link defeat the purpose of hiding the spreadsheet?

**Comment by zachlatta** [comment]
This issue was moved to hackclub/meta#334
