### ISSUE TITLE
Standardize system on how to collect attendance

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#517]
@zachlatta and @MaxWofford, I know that last week you were fairly successful at collecting attendance data. What specific things do we should do going forward to continue to be successful at collecting attendance data?

**Comment by MaxWofford** [comment]
@jonleung The more club leaders using the auto sms-service, the less we will have to ping on slack. Make sure to remind people it exists.

**Comment by zachlatta** [comment]
This issue was moved to hackclub/meta#333
