### ISSUE TITLE
Dodge Workshop: Go into more depth

### ISSUE THREAD

**Issue by bobacadodl** [hackclub/hackclub#522]
When we ran the dodge workshop at our club, people had a lot of additional questions about how to improve their games. One of the biggest questions that people had was how to reset the game automatically without refreshing the page. Other common questions were: "How do you make a score counter?", "How do you display the score you got after you lose?", and "How do you prevent the player from going off the screen?".

Perhaps more steps could be added to the workshop to show how to display the player's current score in the top right, prevent the player from moving off-screen, and include a "game over" screen with the player's final score and a restart button, so that it is a more complete game.

**Comment by jonleung** [comment]
@bobacadodl this is really helpful feedback! Thanks! I saw this problem at @j1lin0101's club as well!

Do you think it would be sufficient if we made examples of how to do these but not explanations?

**Comment by paked** [comment]
@jonleung @bobacadodl I think it may be interesting to do this kind of thing with examples, as opposed to hand holding these steps.

**Comment by bobacadodl** [comment]
@paked @jonleung I agree, examples would be sufficient.  Step by step explanations wouldn't be necessary

**Comment by jonleung** [comment]
@bobacadodl awesome! Sorry about the delayed response, have been a bit sick! We'll add some examples in! @paked @sethtrei @ZucchiniZe, would any of you be interested in adding some examples?

**Comment by sethtrei** [comment]
I could do the refreshing thing I did it on mine

**Comment by jonleung** [comment]
@sethtrei that would be awesome! Thanks! I'd be happy to work with you closely on this pull request if you would like too! Keep me posted if you want to do it!

**Comment by bobacadodl** [comment]
I'd be willing to do the score counter and prevention from going offscreen. I'll try to do it in the proper formatting and make a PR sometime this weekend

**Comment by jonleung** [comment]
@bobacadodl woooot! I'd be happy to work with you closely on this pull request if you would like too!

**Comment by paked** [comment]
@bobacadodl Did you ever get around to doing this? If not I'd be more than happy to do it for you? (Or walk you through doing it yourself if you need it)

**Comment by MaxWofford** [comment]
Is this still being worked on? I'm going to remove the "in progress" tag for now. If it should be here, please re-add it

**Comment by MaxWofford** [comment]
derp, didn't mean to close

![](https://media.giphy.com/media/TlK63ECGCVGjzCu5WVi/giphy.gif)

**Comment by jonleung** [comment]
I think @bobacadodl might be working on some stuff for this right now?
