### ISSUE TITLE
Facilitation guidelines are missing for Dodge, Soccer and Maze

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#523]
As @saescapa brought up in #491, we're currently missing facilitation guidelines in `workshops/workshop_details.md` for Dodge, Soccer, and Maze. This issue is to track the creation of those :-).

**Comment by jonleung** [comment]
We're currently focusing on redoing the entire workshops track so as we redo them, we'll make sure the revamped workshops have facilitation guidelines! Closing this issue for now!
