### ISSUE TITLE
Move meta folder in hackclub to meta repo

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#537]
/cc @hackclub/staff

**Comment by MaxWofford** [comment]
I've created https://github.com/hackclub/hackclub/pull/541 and hackclub/meta#360 to address this

**Comment by MaxWofford** [comment]
@zachlatta Now that https://github.com/hackclub/meta/pull/360 has been merged, this is good to go.

**Comment by zachlatta** [comment]
Merged both hackclub/meta#360 and #541!
