### ISSUE TITLE
Split up the Twilio workshop into more digestible chunks.

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#555]
Right now there is way too much stuff going on in that workshop and there's a lot of good content that people don't have time to get to because there isn't enough time in one workshop.

Also consider addressing #236

**Comment by MaxWofford** [comment]
@jonleung idk if it's useful, but when running this in @ZucchiniZe's school, everyone in the class got to [this part](https://github.com/hackclub/hackclub/tree/master/workshops/twilio#outline-for-the-rest-of-this-tutorial) within the first 10 minutes, then no one in the class got a step past it for the rest of the class.

**Comment by ZucchiniZe** [comment]
Yeah, I think just showing them that they could do that sort of captivated them. Maybe in the future we can split the remote control workshop into two parts, how to use twilio to call and text using JS and how to make it so you can get a text/call when you click a button. Also, one other theory as to why they never got past that part is it was not very clear that you would do anything else other than screw around with twilio.

**Comment by jonleung** [comment]
@ZucchiniZe, that's super helpful thanks!

@MaxWofford which part did they finish up to?

**Comment by ZucchiniZe** [comment]
@jonleung They had finished the first section (calling and sending text messages) and just fooled around with that for the rest of the class.

**Comment by jonleung** [comment]
:+1:

**Comment by MaxWofford** [comment]
Looks like the Twilio workshop just got redone by https://github.com/hackclub/hackclub/pull/641. Closing this issue for now. Feel free to reopen @jonleung if you feel it was left unaddressed.

**Comment by zachlatta** [comment]
Thanks! Yeah, #641 should close this.

On Sun, Jan 10, 2016 at 4:10 AM, Max Wofford <notifications@github.com>
wrote:

> Looks like the Twilio workshop just got redone by #641
> <https://github.com/hackclub/hackclub/pull/641>. Closing this issue for
> now. Feel free to reopen @jonleung <https://github.com/jonleung> if you
> feel it was left unaddressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/555#issuecomment-170340027>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by jonleung** [comment]
I agree with @zachlatta!
