### ISSUE TITLE
Use protocol relative URLs

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#556]
~~Standardize https in hackclub/hackclub~~

EDIT: Links should start with `//` instead of `https://` or `http://`

**Comment by JevinSidhu** [comment]
@ZucchiniZe's mention of using `<script src='//www.google.com/script.js'></script>` I liked! 

It makes you feel fancy too, so there's that :joy:

**Comment by MaxWofford** [comment]
@JevinSidhu @ZucchiniZe  :+1: 

Going to update the issue to reflect that

**Comment by zachlatta** [comment]
Shouldn't we bias for HTTPS when we can for the privacy of our users?

**Comment by ZucchiniZe** [comment]
prefixing urls with `//` automatically resolves the correct protocol for the current page and it is easier to type. So, if all the urls are HTTPS all the scripts and styles will be HTTPS as well.

**Comment by MaxWofford** [comment]
Do `//` url's get hyperlinked in github markdown?

This is a //www.test.com

**Comment by paked** [comment]
@MaxWofford what do we have to do to close this issue?

**Comment by MaxWofford** [comment]
@paked Because some resources we link to don't support `https`, let's close this issue.
