### ISSUE TITLE
Create how to create a pull request workshop

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#568]

**Comment by metmets** [comment]
Yay!

**Comment by MaxWofford** [comment]
Closing this because our new contributing documentation includes references on how to do this.

**Comment by zachlatta** [comment]
:heart:

On Sun, Jan 10, 2016 at 3:31 AM, Max Wofford <notifications@github.com>
wrote:

> Closed #568 <https://github.com/hackclub/hackclub/issues/568>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/568#event-510433244>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io
