### ISSUE TITLE
Update all workshops to use jsbinctl

### ISSUE THREAD

**Issue by paked** [hackclub/hackclub#585]
Waiting on:

- [ ] [Ajar](https://github.com/hackclub/hackclub/tree/master/workshops/ajar), No PR
- [ ] [Cloud9](https://github.com/hackclub/hackclub/tree/master/workshops/cloud9), No PR
- [ ] [Cringe 101](https://github.com/hackclub/hackclub/tree/master/workshops/cringe_101), No PR
- [x] [Dodge](https://github.com/hackclub/hackclub/tree/master/workshops/dodge), #589 
- [ ] [Git and GitHub](https://github.com/hackclub/hackclub/tree/master/workshops/git_and_github), No PR
- [ ] [GitHub Pages](https://github.com/hackclub/hackclub/tree/master/workshops/github_pages), No PR
- [x] [Maze](https://github.com/hackclub/hackclub/tree/master/workshops/maze), #586 
- [x] [Soccer](https://github.com/hackclub/hackclub/tree/master/workshops/soccer), #587

**Comment by paked** [comment]
If you work on porting a workshop, please comment the PR number in which it is contained!

**Comment by ZucchiniZe** [comment]
Finished dodge #589

**Comment by paked** [comment]
@hackclub/staff All of the workshops which use JS Bin for examples have been ported over to jsbinctl. We now just need to decide what to do with the rest of them. As I see it we have a two choices.

- Port everything over to jsbinctl
- Leave it as it is

**Comment by zachlatta** [comment]
What do the others currently use for code examples?

**Comment by paked** [comment]
@zachlatta They just embed them into the raw markdown

Example:
https://github.com/hackclub/hackclub/blob/master/workshops/cringe_101/README.md#set-up-your-document

**Comment by zachlatta** [comment]
Ah, let's leave as-is for the time being, since incorporating `jsbinctl` will just be an improvement, rather than a fix (a valuable one, at that).

**Comment by zachlatta** [comment]
:+1: good work team!

**Comment by zachlatta** [comment]
(and a special thanks to @ZucchiniZe for being involved with this :-)
