### ISSUE TITLE
Apply new styleguides to existing code

### ISSUE THREAD

**Issue by paked** [hackclub/hackclub#595]
Since hackclub/meta#398 and hackclub/meta#399 were merged we are going to have to update a lot of our content to satisfy these new rules.

cc: @hackclub/staff

**Comment by zachlatta** [comment]
So this issue has been vacant for a while. I suggest closing it and trying
our best to get new content to follow the new styleguides (and perhaps
revising the new styleguides to be more permissive).

Thoughts?

On Thu, Dec 17, 2015 at 2:38 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> Since hackclub/meta#398 <https://github.com/hackclub/meta/pull/398> and
> hackclub/meta#399 <https://github.com/hackclub/meta/pull/399> were merged
> we are going to have to update a lot of our content to satisfy these new
> rules.
>
> cc: @hackclub/staff <https://github.com/orgs/hackclub/teams/staff>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/595>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by jonleung** [comment]
Down.

**Comment by zachlatta** [comment]
@paked

On Thu, Feb 11, 2016 at 7:55 PM, Jonathan Leung <notifications@github.com>
wrote:

> Down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/595#issuecomment-183170900>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Going to go ahead with my previous suggestion. Closing for now.
