### ISSUE TITLE
Decoupling the location of the `/workshops` with any code

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#601]
Let's say for example that decide to change the `/workshops` directory to `/curriculum` or something. Because we're using [rawgit](http://rawgit.com) in a lot of places to link to code inside the `/workshops` directory, namely `/workshops/lib`, a bunch of things would break.

How can we de-couple our GitHub directory structure with referencing code in the directory?

/cc @hackclub/staff

**Comment by paked** [comment]
@jonleung @MaxWofford Are we sure we have non relative links in the repository? I thought we were pretty good at avoiding that...

Examples would be good.

**Comment by MaxWofford** [comment]
@jonleung Referencing specific commits can help with that. It's a pain to update though.

**Comment by MaxWofford** [comment]
This discussion doesn't seem to still be active. Closing for now. If anyone wants to bring anything up, please feel free to reopen.

**Comment by zachlatta** [comment]
I'm on board with the decision to close this. Markcop should also catch
broken links, right? And we're linking to specific commits with rawgit, so
things shouldn't break if we move the directory in a new commit (if I
understand our usage correctly).

On Sun, Jan 10, 2016 at 4:21 AM, Max Wofford <notifications@github.com>
wrote:

> Closed #601 <https://github.com/hackclub/hackclub/issues/601>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/601#event-510441495>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
<3
