### ISSUE TITLE
Create whatever is necessary to make the first 2 meetings of a club great!

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#626]
- [ ] Ensure that the curriculum for the first two meetings is prepared
- [ ] Ensure that club leaders know how to run the first two meetings well. This may include general facilitation guidelines as well as specific facilitation guidelines for the first two meetings. We should be able to concretely answer the question "how do I run the + first two meetings" from club leaders.

This issue takes the place of issue #621, #622, and #619.

**Comment by zachlatta** [comment]
Going to go ahead and close this issue because it's ambiguous.
