### ISSUE TITLE
Write a spring semester update to our clubs

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#640]

**Comment by zachlatta** [comment]
Oh whoops, didn't mean to assign myself. Sorry about this!

**Comment by jonleung** [comment]
Here is my preliminary outline of this letter.

> - It's been an exciting year
> - It has been amazing working with you
> - We have learned a lot and not it's time to onboard all these new clubs
> - In the next two months, we are focusing on growth
> - We want to add 50 additional clubs to Hack Club
>   - We're focusing on getting the initial curriculum right so this means that we might not
have>  curriculum that's targeted for you
>   - But we believe that you'll be able to figure it out
>   - We're putting together a Hack Club guide, please leave comments HERE about what your> 
>   - You are Hack Club's inaugural class, as you gain more experience it's time to help new
club>  leaders
>     - Make people feel welcome
>     - They'll be reaching out for questions, help them out
> - Let's make 2016 amazing

Going to write the actual letter now.

**Comment by zachlatta** [comment]
:+1:

On Sun, Jan 10, 2016 at 4:26 PM, Jonathan Leung <notifications@github.com>
wrote:

> Here is my preliminary outline of this letter.
>
>
>    - It's been an exciting year
>    - It has been amazing working with you
>    - We have learned a lot and not it's time to onboard all these new
>    clubs
>    - In the next two months, we are focusing on growth
>    - We want to add 50 additional clubs to Hack Club
>       - We're focusing on getting the initial curriculum right so this
>       means that we might not have> curriculum that's targeted for you
>       - But we believe that you'll be able to figure it out
>       - We're putting together a Hack Club guide, please leave comments
>       HERE about what your>
>       - You are Hack Club's inaugural class, as you gain more experience
>       it's time to help new club> leaders
>       - Make people feel welcome
>       - They'll be reaching out for questions, help them out
>    - Let's make 2016 amazing
>
> Going to write the actual letter now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/640#issuecomment-170409637>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
This issue was moved to hackclub/meta#458
