### ISSUE TITLE
Modify Portfolio workshop to use standardized tools in hackclub/workshops/ARC.md

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#648]
- [ ] Move editor from JS Bin to Cloud9
- [ ] Move hosting from JS Bin to GitHub pages

We might consider using:
- https://github.com/hackclub/hackclub/blob/master/workshops/github_pages/README.md
- Jevin's Portfolio workshop that already uses Cloud9
- Or perhaps starting from scratch might allow us to think about things more clearly and only write what's needed

**Comment by zachlatta** [comment]
I'd personally suggest starting from scratch to make the edited workshop as
smooth as possible.

On Mon, Jan 11, 2016 at 12:05 PM, Jonathan Leung <notifications@github.com>
wrote:

>
>    - Move editor from JS Bin to Cloud9
>    - Move hosting from JS Bin to GitHub pages
>
> We might consider using
>
>    - https://github.com/hackclub/hackclub/tree/master/workshops
>    - Jevin's Portfolio workshop that already uses Cloud9
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/648>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by jonleung** [comment]
:+1:

**Comment by jonleung** [comment]
@zachlatta, I am starting from scratch in #652

Thanks for the feedback. I have a lot to learn from @hackclub/cipher's portfolio workshop. I will be slowly incorporating many of their ideas!

**Comment by zachlatta** [comment]
Sweet!

On Tue, Jan 12, 2016 at 3:49 PM, Jonathan Leung <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta>, I am starting from scratch in
> #652 <https://github.com/hackclub/hackclub/pull/652>
>
> Thanks for the feedback. I have a lot to learn from @hackclub/cipher
> <https://github.com/orgs/hackclub/teams/cipher>'s portfolio workshop. I
> will be slowly incorporating many of their ideas!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/648#issuecomment-171102661>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Closed by #677.
