### ISSUE TITLE
Make the twilio-basic script work for international hackers!

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#653]

**Comment by paked** [comment]
please

**Comment by zachlatta** [comment]
Couple notes on this (from my experience setting up twilio-basic in
Estonia):

   - I believe that our custom code for buying phone numbers only works
   with USA phone numbers (it filters for the country code +1)
   - In some countries, like Estonia, there aren't Twilio numbers that have
   both SMS and call support. You can buy two numbers though (one for SMS and
   one for making calls)


On Wed, Jan 13, 2016 at 11:30 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/653#issuecomment-171562377>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by jonleung** [comment]
@paked, is this something you'd be interested in working on?

**Comment by MaxWofford** [comment]
@jonleung it seems like it you could most efficiently work on it. The script isn't well documented and can be done quicker by someone with previous experience with it.

**Comment by zachlatta** [comment]
Agreed with @msw.

On Thu, Jan 14, 2016 at 7:47 PM, Max Wofford <notifications@github.com>
wrote:

> @jonleung <https://github.com/jonleung> it seems like it you could most
> efficiently work on it. The script isn't well documented and can be done
> quicker by someone with previous experience with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/653#issuecomment-171865372>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by jonleung** [comment]
Sure, I won't have time to work on this until later though. I'm not currently sure when I might be able to get to it.

**Comment by zachlatta** [comment]
:+1: let's actually make sure this gets done though

On Thu, Jan 21, 2016 at 12:34 PM, Jonathan Leung <notifications@github.com>
wrote:

> Sure, I won't have time to work on this until later though. I'm not
> currently sure when I might be able to get to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/653#issuecomment-173700049>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
@zachlatta This is not me https://github.com/hackclub/hackclub/issues/653#issuecomment-171897682

**Comment by zachlatta** [comment]
Oh crap, sorry @msw! Meant to tag @MaxWofford.

--
Zach Latta
Hack Club | zach@hackclub.io

**Comment by MaxWofford** [comment]
@jonleung Is this still going to be fixed? Someone had brought up just putting a notice that the workshop only works in the US.

**Comment by zachlatta** [comment]
Let's just close. #703 added the notice that it only works in North America.

On Fri, Feb 12, 2016 at 9:46 PM, Max Wofford <notifications@github.com>
wrote:

> @jonleung <https://github.com/jonleung> Is this still going to be fixed?
> Someone had brought up just putting a notice that the workshop only works
> in the US.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/653#issuecomment-183599582>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
