### ISSUE TITLE
Create a solid version of the curriculum arc

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#663]

**Comment by MaxWofford** [comment]
What does this issue mean?

**Comment by zachlatta** [comment]
@jonleung?

On Wed, Jan 20, 2016 at 2:26 PM, Max Wofford <notifications@github.com>
wrote:

> What does this issue mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/663#issuecomment-173382008>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by jonleung** [comment]
This issue means creating an outline of which computer science concepts are used in which workshops. This is done in this pull request: https://github.com/hackclub/hackclub/pull/682

**Comment by MaxWofford** [comment]
Closing this because #682 has been merged.
