### ISSUE TITLE
Hack Club Banner

### ISSUE THREAD

**Issue by MrCodeCollector** [hackclub/hackclub#670]
Create an MLH inspired banner for club websites. Much like the one that MLH sponsored events get on their website, but have a Hack Club version, for Hack Club associated clubs.

**Comment by ZucchiniZe** [comment]
I would love to help out with this if I have the time!

**Comment by zachlatta** [comment]
:+1: I love this idea.

Here's what MLH's looks like for reference:


​

On Mon, Jan 25, 2016 at 8:41 PM, Alex B <notifications@github.com> wrote:

> I would love to help out with this if I have the time!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/670#issuecomment-174762913>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.io

**Comment by zachlatta** [comment]
:+1: I love this idea.

Here's what MLH's looks like for reference:

![tmp](https://cloud.githubusercontent.com/assets/992248/12570408/5ca36afe-c3a5-11e5-90fc-3cee2e8e0fe0.png)​

**Comment by MaxWofford** [comment]
I can see it already...

![hanging_dino](https://cloud.githubusercontent.com/assets/5891442/12570482/f55fc0b2-c3a5-11e5-9b61-9d0f01a76587.png)

**Comment by zachlatta** [comment]
Mockup:

![tmp](https://cloud.githubusercontent.com/assets/992248/12573326/a4e73d84-c3c5-11e5-81ae-d82d1a1bc584.png)

**Comment by paked** [comment]
@zachlatta #subtle

**Comment by MaxWofford** [comment]
#flatdesign

**Comment by MrCodeCollector** [comment]
#FutureIsNow

**Comment by jkwok91** [comment]
![orpheusbanner](https://cloud.githubusercontent.com/assets/2666337/12998666/4ab8d032-d0fb-11e5-9dd4-0dce820160cc.png)

**Comment by jkwok91** [comment]
and this is a less fun one
![boringggggggg](https://cloud.githubusercontent.com/assets/2666337/12998686/73e6707c-d0fb-11e5-80a4-468a5c002adc.png)

with wonky angles that will be fixed in not-the-sketch

**Comment by jkwok91** [comment]
![side](https://cloud.githubusercontent.com/assets/2666337/12998714/d974803c-d0fb-11e5-9f8e-565a7908305e.png)

with less orpheus and a crappier flag
in which i also spelled hacklub incorrectly

**Comment by jkwok91** [comment]
and one that is independent of where you put it on the page
![hand and flag](https://cloud.githubusercontent.com/assets/2666337/12998782/8dff403c-d0fc-11e5-864c-66063913317e.png)

**Comment by zachlatta** [comment]
:+1: :+1: :+1: to all of the above

On Thu, Feb 11, 2016 at 8:18 PM, JESSICA <notifications@github.com> wrote:

> and one that is independent of where you put it on the page
> [image: hand and flag]
> <https://cloud.githubusercontent.com/assets/2666337/12998782/8dff403c-d0fc-11e5-864c-66063913317e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/670#issuecomment-183173124>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
SO GOOD

:+1:

**Comment by jkwok91** [comment]
ok i've made some vectors; posting here for anyone who missed the slack messages
![generic banner](https://cloud.githubusercontent.com/assets/2666337/13024933/ea24f69e-d1b1-11e5-9a5c-b2fdc27fc7fc.png)
![orpheus hand](https://cloud.githubusercontent.com/assets/2666337/13024934/ea27eae8-d1b1-11e5-9220-78bfa9eca671.png)

**Comment by zachlatta** [comment]
So good. I'm going to open another issue to track writing some code to
easily add this to sides.

Something along the lines of https://github.com/blog/273-github-ribbons.

On Fri, Feb 12, 2016 at 11:37 PM, JESSICA <notifications@github.com> wrote:

> Closed #670 <https://github.com/hackclub/hackclub/issues/670>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/670#event-549370138>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Just opened #712 :-).
