### ISSUE TITLE
Multiplayer Support for Agar.io

### ISSUE THREAD

**Issue by notsmyles** [hackclub/hackclub#695]
I think it would be a cool idea if there was multiplayer support for the Agar.io website! I think if this extension was added, it would boost club unity because it would give members something to work on and play together. Even it was not Agar.io, it would be easy to translate the code into other uses and designs as well.

**Comment by paked** [comment]
This sounds awesome. I did some research recently into using a BaaS for multiplayer games. Perhaps someone could try and hack together something like this using firebase.

It would be really awesome to teach everyone to use the same backend and everyone builds their own client.

**Comment by zachlatta** [comment]
Yeah, I love this idea.

Gonna look into some backends as a service we might be able to use for
games as well. I know a bunch exist for Unity.

On Sun, Feb 7, 2016 at 4:19 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> This sounds awesome. I did some research recently into using a BaaS for
> multiplayer games. Perhaps someone could try and hack together something
> like this using firebase.
>
> It would be really awesome to teach everyone to use the same backend and
> everyone builds their own client.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/695#issuecomment-181145746>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
/cc @skylarbpayne :smile:

On Tue, Feb 9, 2016 at 11:59 AM, Zach Latta <zach@hackclub.com> wrote:

> Yeah, I love this idea.
>
> Gonna look into some backends as a service we might be able to use for
> games as well. I know a bunch exist for Unity.
>
> On Sun, Feb 7, 2016 at 4:19 PM, Harrison Shoebridge <
> notifications@github.com> wrote:
>
>> This sounds awesome. I did some research recently into using a BaaS for
>> multiplayer games. Perhaps someone could try and hack together something
>> like this using firebase.
>>
>> It would be really awesome to teach everyone to use the same backend and
>> everyone builds their own client.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/hackclub/issues/695#issuecomment-181145746>.
>>
>
>
>
> --
> Zach Latta
> Hack Club | zach@hackclub.com
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by MaxWofford** [comment]
Is it cool if I close this because the agar.io workshop isn't in the new curriculum?

**Comment by zachlatta** [comment]
Let's leave it open until we get #778 closed. Can you leave a note over in
#778 saying that we should make sure to close this when that's closed?

On Wed, Apr 6, 2016 at 9:05 PM, Max Wofford <notifications@github.com>
wrote:

> Is it cool if I close this because the agar.io workshop isn't in the new
> curriculum?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/695#issuecomment-206688692>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
@zachlatta sounds good!

**Comment by zachlatta** [comment]
I'm gonna rescind what I said earlier. Let's just go ahead and close this because we're shifting our priorities to the new curriculum plan.
