### ISSUE TITLE
Create HTML snippets for Hack Club banner

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#712]
Expand on #670 and create HTML snippets for the Hack Club banner @jkwok91 added in hackclub/meta#492 (just like https://github.com/blog/273-github-ribbons).

**Comment by MaxWofford** [comment]
Pasting these here so we have a githubusercontent.com link
![banner_plain_flag](https://cloud.githubusercontent.com/assets/5891442/13030172/f6439684-d26e-11e5-9d0e-fd2ce0dd15aa.png)
![banner_orpheus_hand](https://cloud.githubusercontent.com/assets/5891442/13030173/f64434e0-d26e-11e5-9fe2-120ff1286b49.png)

**Comment by zachlatta** [comment]
Should we turn these into stickers as well?
-- 
Zach Latta

**Comment by MaxWofford** [comment]
Here's that last one again.

![banner_orpheus_hand](https://cloud.githubusercontent.com/assets/5891442/13030188/44e773c8-d26f-11e5-9a03-f69bb8a72ada.png)

**Comment by MaxWofford** [comment]
@jkwok91 Is that pointy triangle on the top of the forearm part of the picture?

**Comment by MaxWofford** [comment]
`<a href="https://hackclub.com/#"><img style="position: absolute; top: 0; right: 0; border: 0; width: 230px;" src="https://cloud.githubusercontent.com/assets/5891442/13030188/44e773c8-d26f-11e5-9a03-f69bb8a72ada.png" alt="Hack Club"</a>`

![screenshot from 2016-02-13 16 39 44](https://cloud.githubusercontent.com/assets/5891442/13030219/80cd7760-d270-11e5-993f-f3e025eb7406.png)

***I did not reach out for Tom Preston-Werner's permission to do this***

**Comment by MaxWofford** [comment]
`<a href="https://hackclub.com/#"><img style="position: absolute; top: 0; left: 0; border: 0; width: 230px;" src="https://cloud.githubusercontent.com/assets/5891442/13030172/f6439684-d26e-11e5-9d0e-fd2ce0dd15aa.png" alt="Hack Club"</a>`

![screenshot from 2016-02-13 16 44 03](https://cloud.githubusercontent.com/assets/5891442/13030226/0170d222-d271-11e5-92b2-65b503a46775.png)

***I did not reach out for @zachlatta's permission to do this***

**Comment by zachlatta** [comment]
This is the best thing I've seen all day.

/cc @mojombo
-- 
Zach Latta

**Comment by MaxWofford** [comment]
Front page of hn

![screenshot from 2016-02-13 16 53 09](https://cloud.githubusercontent.com/assets/5891442/13030265/8c05a97a-d272-11e5-87c5-ae759c3fc9d5.png)

**Comment by paked** [comment]
![selection_011](https://cloud.githubusercontent.com/assets/8407370/13030311/6aa681b8-d2fa-11e5-9b58-8ee19b428815.png)

:') I have slight concerns about what it would look like on mobile though...

**Comment by zachlatta** [comment]
Ah, that's a good point. Can someone post a screenshot of it on mobile?

On Sat, Feb 13, 2016 at 2:08 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> [image: selection_011]
> <https://cloud.githubusercontent.com/assets/8407370/13030311/6aa681b8-d2fa-11e5-9b58-8ee19b428815.png>
>
> :') I have slight concerns about what it would look like on mobile
> though...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/712#issuecomment-183764889>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Could we make it so it's on the side of the screen on mobile?

On Sat, Feb 13, 2016 at 2:17 PM, Zach Latta <zach@zachlatta.com> wrote:

> Ah, that's a good point. Can someone post a screenshot of it on mobile?
>
> On Sat, Feb 13, 2016 at 2:08 PM, Harrison Shoebridge <
> notifications@github.com> wrote:
>
>> [image: selection_011]
>> <https://cloud.githubusercontent.com/assets/8407370/13030311/6aa681b8-d2fa-11e5-9b58-8ee19b428815.png>
>>
>> :') I have slight concerns about what it would look like on mobile
>> though...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/hackclub/issues/712#issuecomment-183764889>.
>>
>
>
>
> --
> Zach Latta
> https://zachlatta.com <http://zachlatta.com>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
@zachlatta :+1: To put it on its side, we'll probably have to modify the image.

/cc @jkwok91

**Comment by jkwok91** [comment]
@MaxWofford @zachlatta HORROR OF HORRORS
WHAT'S THAT DAMN POINTY THING
I DID NOT PUT THAT THERE
IT'S NOT IN MY SVG

**Comment by jkwok91** [comment]
and maybe i'll modify it so that orpheus doesn't have a dismembered arm (remove the edge of the arm)
but uhhhh
shouldnt css take care of that?

**Comment by paked** [comment]
@zachlatta Simulated mobile (featuring Google Chrome Developer Tools):
![selection_013](https://cloud.githubusercontent.com/assets/8407370/13030784/d1cdf28a-d30a-11e5-8dd1-58c8ef0a56c5.png)

**Comment by jkwok91** [comment]
@paked @zachlatta @MaxWofford is the edge of the arm not bothering y'all?? can't you {position:absolute; top: -5px;} or something

**Comment by zachlatta** [comment]
Can confirm, edge of arm is bothering me
-- 
Zach Latta

**Comment by jkwok91** [comment]
btw y'all: rotated version of banner:
![screen shot 2016-02-13 at 4 23 52 pm](https://cloud.githubusercontent.com/assets/2666337/13030876/36434fa0-d26e-11e5-9840-ad2225363d1a.png)

still gonna need dat CSS {position:absolute; left: -5px;} or wahtev

**Comment by MaxWofford** [comment]
@jkwok91 Do you have that chrome extension that changes `cloud` to `butt`?

![screenshot from 2016-02-13 20 12 48](https://cloud.githubusercontent.com/assets/5891442/13031122/2f4e6f52-d28e-11e5-982c-59d3a33c2b70.png)

![screenshot from 2016-02-13 20 12 57](https://cloud.githubusercontent.com/assets/5891442/13031123/33b88b7c-d28e-11e5-9b80-57dfd1abb0c6.png)

**Comment by MaxWofford** [comment]
Love the rotated arm though! 

![](https://cloud.githubusercontent.com/assets/2666337/13030876/36434fa0-d26e-11e5-9840-ad2225363d1a.png)

**Comment by jkwok91** [comment]
blame @zachlatta for cloud->butt extension

**Comment by MaxWofford** [comment]
@jkwok91 Could we get png exported ones with no whitespace on the edge they should be touching? `left: -3px;` feels kinda hacky to me.

**Comment by jkwok91** [comment]
done https://github.com/hackclub/meta/pull/494

**Comment by zachlatta** [comment]
Assigning @jkwok91 to handle getting these HTML snippets in. Let's just add them to a section at the bottom of `README.md` for now.

Quick requirements for the final version of these:

- Must work well on mobile (this may just mean hiding them on mobile)
- Shouldn't have the extra line on the side for Orpheus's arm (use the `-5px` thing or whatever)

**Comment by jkwok91** [comment]
![banner1_final](https://cloud.githubusercontent.com/assets/2666337/13058625/3cf7f8ac-d3d9-11e5-9942-437039bf87b5.png)
![banner2_final](https://cloud.githubusercontent.com/assets/2666337/13058605/1a9f4f12-d3d9-11e5-971f-171af9fe4eef.png)
![banner2_rotated](https://cloud.githubusercontent.com/assets/2666337/13058606/1aa23aec-d3d9-11e5-911f-aafcc9781794.png)

getting the githubusercontent link (as max did, above) for the updated pngs

**Comment by zachlatta** [comment]
What if we used rawgit instead of githubusercontent? Seems odd to use
githubusercontent when we could link to images that are actually in our
repos through a CDN.

On Mon, Feb 15, 2016 at 11:42 AM, JESSICA <notifications@github.com> wrote:

> [image: banner1_final]
> <https://cloud.githubusercontent.com/assets/2666337/13058625/3cf7f8ac-d3d9-11e5-9942-437039bf87b5.png>
> [image: banner2_final]
> <https://cloud.githubusercontent.com/assets/2666337/13058605/1a9f4f12-d3d9-11e5-971f-171af9fe4eef.png>
> [image: banner2_rotated]
> <https://cloud.githubusercontent.com/assets/2666337/13058606/1aa23aec-d3d9-11e5-911f-aafcc9781794.png>
>
> getting the githubusercontent link (as max did, above) for the updated pngs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/712#issuecomment-184359430>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by paked** [comment]
I agree with @zachlatta here. Proper CDN > hacky CDN.

**Comment by jkwok91** [comment]
real CDN has been used

https://github.com/hackclub/hackclub/pull/719

**Comment by jkwok91** [comment]
live on mobile:
![screen shot 2016-02-15 at 2 49 33 pm](https://cloud.githubusercontent.com/assets/2666337/13062415/605baa22-d3f3-11e5-9c32-2f642cae82c6.png)

**Comment by zachlatta** [comment]
:tada: :tada: :tada:

On Mon, Feb 15, 2016 at 2:50 PM, JESSICA <notifications@github.com> wrote:

> live on mobile:
> [image: screen shot 2016-02-15 at 2 49 33 pm]
> <https://cloud.githubusercontent.com/assets/2666337/13062415/605baa22-d3f3-11e5-9c32-2f642cae82c6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/712#issuecomment-184428294>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MrCodeCollector** [comment]
I'm digging all of this.
