### ISSUE TITLE
#studycorner is missing from Slack Field Guide

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#713]
Over at https://github.com/hackclub/hackclub/blob/master/SLACK.md#field-guide we have a quick overview of the default channels on our Slack.

`#studycorner` is a default channel, but doesn't have an entry in the Field Guide.

**Comment by jkwok91** [comment]
which screenshot should i use
![screen shot 2016-02-15 at 10 33 29 am](https://cloud.githubusercontent.com/assets/2666337/13057352/61ecd348-d3d0-11e5-86f1-d98776c6b2d5.png)
![screen shot 2016-02-15 at 10 38 40 am](https://cloud.githubusercontent.com/assets/2666337/13057353/61ef93d0-d3d0-11e5-8a24-fa58b66cb11c.png)

**Comment by zachlatta** [comment]
Let's go with #2.

On Mon, Feb 15, 2016 at 10:39 AM, JESSICA <notifications@github.com> wrote:

> which screenshot should i use
> [image: screen shot 2016-02-15 at 10 33 29 am]
> <https://cloud.githubusercontent.com/assets/2666337/13057352/61ecd348-d3d0-11e5-86f1-d98776c6b2d5.png>
> [image: screen shot 2016-02-15 at 10 38 40 am]
> <https://cloud.githubusercontent.com/assets/2666337/13057353/61ef93d0-d3d0-11e5-8a24-fa58b66cb11c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/713#issuecomment-184341676>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
Excellent choice, sire. https://github.com/hackclub/hackclub/pull/717

**Comment by zachlatta** [comment]
Closed by #717.
