### ISSUE TITLE
Make it clearer how to use the template slideshow presentations

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#722]
We have a few template slideshow presentations for meetings in https://drive.google.com/folderview?id=0B34YNYNQ6z3YWWxHRGdnUVVpbzA&usp=sharing&tid=0B34YNYNQ6z3YbE1JVmZfdW9Qc3c that are linked from the club guide (https://github.com/hackclub/hackclub/blob/master/clubs/README.md).

They're meant to be used as follows:

1. Club leader makes a copy of the appropriate slideshow for their meeting (`File > Make a copy...`)
2. Club leader replaces all text in brackets (ex. `[HIGH_SCHOOL]`) with appropriate text for their club and makes any other changes they want

Right now the links to the slideshows aren't super prominent and we've had a couple clubs get confused by the guide on using them.

**Comment by jkwok91** [comment]
I think I'll make a new section in clubs/README.md for this. It gets repeated often enough to warrant it.

**Comment by zachlatta** [comment]
:+1:

On Wed, Feb 17, 2016 at 9:41 PM, JESSICA <notifications@github.com> wrote:

> I think I'll make a new section in clubs/README.md for this. It gets
> repeated often enough to warrant it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/722#issuecomment-185551493>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
