### ISSUE TITLE
Remove GIFs of HTML in personal workshop

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#733]
It seems like most GIFs of HTML code are redundant in the personal workshop because we already have our HTML in `backticks`. Additionally they make changing the workshop a much longer process.

@remixz: because this is a curriculum decision, is it cool if I assign you?

**Comment by remixz** [comment]
:+1: The GIFs do look flashy, but ultimately don't provide much utility.

**Comment by zachlatta** [comment]
The one thing I would suggest: testing the workshop with and without the
GIFs with a total beginner. I think it's often really easy to forget about
some of the stumbling blocks that beginners run into and perhaps the GIFs
are a helpful visual aid when people are getting started.

On Wed, Feb 24, 2016 at 9:30 AM, Zach Bruggeman <notifications@github.com>
wrote:

> [image: :+1:] The GIFs do look flashy, but ultimately don't provide much
> utility.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/733#issuecomment-188367214>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by MaxWofford** [comment]
@remixz @zachlatta Want to bring this to slack and see if any of our club leaders can test it for us?

**Comment by zachlatta** [comment]
I think we should probably find someone who's never coded before to do the
workshop. I bet if any of us make a Facebook post, we'd get a ton of people
interested.

On Wed, Feb 24, 2016 at 9:37 AM, Max Wofford <notifications@github.com>
wrote:

> @remixz <https://github.com/remixz> @zachlatta
> <https://github.com/zachlatta> Want to bring this to slack and see if any
> of our club leaders can test it for us?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/733#issuecomment-188371264>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
@zachlatta I personally think the gifs aren't worth the effort. Updating the gifs every time we make a change to sections of code is a big burden.

**Comment by MaxWofford** [comment]
^Specifically the gifs of typing in code right next to a code block in markdown. Regular gifs are fine by me.

**Comment by MaxWofford** [comment]
![](http://i.imgur.com/F8quAKm.gif)

**Comment by zachlatta** [comment]
I still think it's worth testing, especially this is a change that'll
affect current and all future workshops. Who knows, maybe having a visual
aid of us typing stuff in is helpful to guide new hackers.

On Wed, Feb 24, 2016 at 10:24 AM, Max Wofford <notifications@github.com>
wrote:

>
> <https://camo.githubusercontent.com/806adcad950f84a0eeb73cb755b0ab2e3b2a2b66/687474703a2f2f692e696d6775722e636f6d2f46387175414b6d2e676966>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/733#issuecomment-188392020>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by TheThirdOne** [comment]
Something that may be interesting is making an automated text-change => gif generator. It may help with the file size issues in #241 and #744 if we generate simple gifs.

**Comment by MaxWofford** [comment]
@TheThirdOne Totes agree. @hackclub/staff Anyone want to hack on a gif build system this weekend?

**Comment by MaxWofford** [comment]
As for markcop checking file size, https://github.com/hackclub/markcop/issues/79

**Comment by MaxWofford** [comment]
Turns out there's already a thing for converting [asciinema to gif](https://github.com/wong2/asciinema2gif):

[![](http://i.imgur.com/Cfh1gOm.gif)](https://asciinema.org/api/asciicasts/8qhs49xho1jyqpx4lit72w1aq)

_click the image_

**Comment by zachlatta** [comment]
I think GIFs are most useful for showing people how to do visual things on the screen, like creating new folders for the first time in Cloud9.

Doesn't this fall into the same trap that GIFs of code being typed do? Could just as daily be a code block in Markdown.

**Comment by zachlatta** [comment]
*just as easily

**Comment by MaxWofford** [comment]
@zachlatta To my understanding, this discussion is about the GIFs of code being typed in:

> GIFs of HTML code are redundant in the personal workshop because we already have our HTML in `backticks`

**Comment by zachlatta** [comment]
Sure, but can't the same argument be made for terminal commands? That we could just put them and their results into backticks?

**Comment by MaxWofford** [comment]
@zachlatta I think we're on the same foot there, terminal commands should be replaced.

**Comment by MaxWofford** [comment]
s/\./ with `backticks`/

**Comment by MaxWofford** [comment]
hmmm. GitHub thought that was markdown.
I meant
> terminal GIFs should be replaced with commands in backticks.

**Comment by paked** [comment]
I think one thing gifs do well with that doesn't seem to have been brought up yet is providing context about where you are writing your code.

For example, the "Insert `<a href="...">ble</a>` to the head section` means *nothing* to a beginner.

- What is a head section?
- How do I insert? Is that a right click?

A gif provides context in the sense that you can see *exactly* where you need to write your code. I also have a theory that people find it a lot friendlier, but I have no idea how to test that out!

Perhaps an objection to this is that we would be hand holding our consumers, which is a valid point. But at the beginning, don't we have to hand hold to a certain degree anyway? 

Hand holding is fine as long as the code is still being typed out by hand into the editor. If we allow our code to be copy/pasted I hypothesise that people will become much less comfortable when it comes to working on their **own** projects.

**Comment by MaxWofford** [comment]
@hackclub/staff 
Anyone down for a call about this and https://github.com/hackclub/hackclub/issues/744? I'd really like to make changes to the personal_website workshop, but can't until this is resolved.

**Comment by zachlatta** [comment]
Yeah, doing a call sounds good. Can everyone interested indicate their
availability in http://doodle.com/poll/bu7hv3u57hvyy8sr?

On Sun, Feb 28, 2016 at 9:41 AM, Max Wofford <notifications@github.com>
wrote:

> /cc @TheThirdOne <https://github.com/TheThirdOne> ^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/733#issuecomment-189912795>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Awesome, so we're set for Thursday at 2PM Pacific in
https://partytime.hackclub.com :-). I doubt this'll work for you @paked,
but it seems to be the only time that works for the others. Would it be
okay if we just filled you in after the call? If you'd prefer to be in it,
we can find another time that'd work.

Who wants to take point on this call? Taking point would mean setting an
agenda and facilitating discussion during the call itself.

On Sun, Feb 28, 2016 at 11:02 AM, Zach Latta <zach@zachlatta.com> wrote:

> Yeah, doing a call sounds good. Can everyone interested indicate their
> availability in http://doodle.com/poll/bu7hv3u57hvyy8sr?
>
> On Sun, Feb 28, 2016 at 9:41 AM, Max Wofford <notifications@github.com>
> wrote:
>
>> /cc @TheThirdOne <https://github.com/TheThirdOne> ^
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/hackclub/issues/733#issuecomment-189912795>.
>>
>
>
>
> --
> Zach Latta
> https://zachlatta.com <http://zachlatta.com>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by remixz** [comment]
I can lead the call (unless someone else really wants to). This call might actually be a good one to discuss curriculum in general, as I can give some more insight into ideas I have for the curriculum in the long term (GH-739). We can also discuss specifics such as this issue.

I propose we use a Google Hangouts on Air, so that a) anyone who isn't available at that time can watch the VOD later, and b) anyone who wants to watch, but doesn't want to join the call, can watch live via the public link. I can set that all up.

**Comment by MaxWofford** [comment]
@remixz I'm fine with chatting about curriculum in general, as long as we get #733 resolved.

**Comment by paked** [comment]
Gah! I wish I could make this call.

Please, please, please Hangouts on Air.

**Comment by remixz** [comment]
Here's the preliminary agenda: https://docs.google.com/document/d/1oFq6VumW3gG-9j-z4xm3d1rNteSrNqrLdLsvPLGhhKY/edit?usp=sharing

As I mentioned in the document, if you'd like to be a participant in the call, let me know here or on Slack (I'm `@bruggie`). This is an open call! :smile:

**Comment by TheThirdOne** [comment]
@remixz, I'd like to be a participant.

**Comment by remixz** [comment]
After our discussion in the call (https://www.youtube.com/watch?v=IO-vVJlB9a0), here are our thoughts going forward:

* For future workshops, we'll be ensuring that the GIFs we add are providing value, and aren't just things like typing out a line of code. We won't be removing GIFs from current workshops, though.
* In regards to size concerns with GIFs, we're going to put that discussion on hold for now, as our current focus is adding to our content, and encouraging community involvement. We don't want to add too many restrictions early on. We'll revisit this issue if it becomes a major problem.

I'm going to close out this issue, as I think we've solved it. Please feel free to comment if you need anymore clarification.
