### ISSUE TITLE
Drizzy Drake -> Prophet Orpheus

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#734]
Just read https://gist.github.com/remixz/4651245

Let's replace `Drizzy Drake` in the personal website workshop with [`Prophet Orpheus`](https://github.com/hackclub/dinosaurs/blob/master/README.md)

**Comment by zachlatta** [comment]
Just to point out one of the impediments to easily doing this: we'll have
to re-record the GIFs in the workshop.

On Tue, Feb 23, 2016 at 9:13 PM, Max Wofford <notifications@github.com>
wrote:

> Just read https://gist.github.com/remixz/4651245
>
> Let's replace Drizzy Drake in the personal website workshop with Prophet
> Orpheus <https://github.com/hackclub/dinosaurs/blob/master/README.md>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/734>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Though that could warrant an entirely separate discussion. Do the GIFs even
have that much of a benefit? What if we removed them entirely?

On Tue, Feb 23, 2016 at 9:23 PM, Zach Latta <zach@hackclub.com> wrote:

> Just to point out one of the impediments to easily doing this: we'll have
> to re-record the GIFs in the workshop.
>
> On Tue, Feb 23, 2016 at 9:13 PM, Max Wofford <notifications@github.com>
> wrote:
>
>> Just read https://gist.github.com/remixz/4651245
>>
>> Let's replace Drizzy Drake in the personal website workshop with Prophet
>> Orpheus <https://github.com/hackclub/dinosaurs/blob/master/README.md>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackclub/hackclub/issues/734>.
>>
>
>
>
> --
> Zach Latta
> Hack Club | zach@hackclub.com
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Ah, I just saw #733.

On Tue, Feb 23, 2016 at 9:25 PM, Zach Latta <zach@hackclub.com> wrote:

> Though that could warrant an entirely separate discussion. Do the GIFs
> even have that much of a benefit? What if we removed them entirely?
>
> On Tue, Feb 23, 2016 at 9:23 PM, Zach Latta <zach@hackclub.com> wrote:
>
>> Just to point out one of the impediments to easily doing this: we'll have
>> to re-record the GIFs in the workshop.
>>
>> On Tue, Feb 23, 2016 at 9:13 PM, Max Wofford <notifications@github.com>
>> wrote:
>>
>>> Just read https://gist.github.com/remixz/4651245
>>>
>>> Let's replace Drizzy Drake in the personal website workshop with Prophet
>>> Orpheus <https://github.com/hackclub/dinosaurs/blob/master/README.md>
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/hackclub/hackclub/issues/734>.
>>>
>>
>>
>>
>> --
>> Zach Latta
>> Hack Club | zach@hackclub.com
>>
>
>
>
> --
> Zach Latta
> Hack Club | zach@hackclub.com
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by zachlatta** [comment]
Closed by #756.
