### ISSUE TITLE
Workshop Revamp

### ISSUE THREAD

**Issue by remixz** [hackclub/hackclub#739]
Slide deck: https://speakerdeck.com/remixz/hack-club-workshop-proposals (Original PDF: https://slack-files.com/T0266FRGM-F0NVCK73K-30be3f5825)

Opening this issue so we can have a long-running conversation on the ideas of revamping the workshops.

Slack transcript as of this issue:

>sely [8:40 PM] 
>bruggie - just a thought on your reordering of workshops. you mentioned that twilio should be first then portfolio the second week. twilio seems a bit aggressive for a start - a lot of the beginners i've worked with at different hackathons were extremely confused during the process. they weren't really sure where stuff went, how to use twilio, etc because they were just starting out. it seems normal for us because we all have a decent background, but it's apparently really confusing for beginners.

>harrison [8:41 PM] 
>I really liked the tiered workshops model

>sely [8:41 PM] 
>that said, it is fun and would work well after people have more background in a sense, but at the moment twilio seems very mentor-dependent because it's not necessarily the most self-explanatory

>harrison [8:42 PM] 
>I think that Twilio is the most engaging, but I think it needs a bit of work to make it beginner friendly.

>[8:42] 
>I'd be uncomfortable recommending people to use twilio in its current state

>sely [8:43 PM] 
>harrison: agreed. i think it'll be difficult to make it more beginner-friendly though, otherwise it's just a bunch of "you put this code here, type this there" etc

>[8:43] 
>there isn't really a fundamental understanding quite yet, or as it seems

>harrison [8:44 PM] 
>I personally would love to see the first workshop be more engaging

>bruggie [8:45 PM] 
>i agree with your both your points on twilio! zrl had mentioned to me that we might want to rework it, since setting up so many twilio accounts can be a pain point. i mostly just want the first workshop to have more engagement, like you just said harrison :smile:

>zrl [8:45 PM] 
just finished giving it a read

>[8:45] 
>this is ​_awesome_​

>[8:46] 
>i say go ahead, create a github issue for this, and throw the PDF in the issue

>[8:46] 
>how near future are you thinking for the call bruggie?

>harrison [8:46 PM] 
>I'd really like to be on this

>[8:46] 
>If at all possible

>bruggie [8:47 PM] 
>up to everyone! i'm free this week, but next week is fine for me too

>[8:47] 
>and for sure harrison, definitely want to hear your thoughts :simple_smile:

>[8:47] 
>anyone else for that matter. maybe it can be an open call or something.

**Comment by zachlatta** [comment]
And for those that aren't in the Slack, here's a link to the same PDF uploaded to GitHub: 
[Hack Club Workshop Proposals.pdf](https://github.com/hackclub/hackclub/files/145989/Hack.Club.Workshop.Proposals.pdf)

**Comment by MattHesby** [comment]
The only thing that I'm not excited about is the "social change" aspect.  I think social awareness and change is a good thing.  And I agree that focusing too much on Games for the curriculum is bad.  But I think focusing too much on Social Awareness as the goal, as you said, ruffles some feathers.  There's a better way to allow hack clubs to decide what Social Awareness means for them and make it more of a good way to pull in people's actual problems.  If you ask "What Problems in Society, either my own, or the larger world can we solve?".  This allows for the "Social Awareness" aspect that you want, but also allows for clubs that are not hooked on that to thrive and grow as well, while still making positive changes in the way that makes sense to them.
And still even allows room for Games if that's what a club decides they are more interested in... because "What problems can we solve" can definitely include, "boredom"

**Comment by remixz** [comment]
I'll lay out a few more reasons behind the social change aspect, and why I'm drawn to it:

1. There's already a lot of curriculum out there based around making games, amongst other things. I have nothing against games, as I think they're an amazing art form, and I think we should have them in our curriculum. However, aside from what we already have, there's a plethora of game tutorials that range across all skill levels available elsewhere online. Instead of essentially reinventing the wheel, I'd rather offer a couple from our end, and then curate the resources that already exist, ones that'll probably be better than what I can create (as I'm not a super proficient game developer), and offer those to students. As well, for those students who are more inclined to making games, I'd want to encourage them to start writing their own workshops, and work with them to integrate it into our offerings.

2. I want to encourage students to think bigger about computer science. One thing that irks me about the tech industry is that there seems to be the notion that the "biggest and best challenges" are at companies like Facebook and Google. They are indeed big challenges, since they are having to optimize for a ridiculous amount of users, and these challenges do require a lot of brainpower, but I'm not a fan of that being the peak of computer science. There's so much more that I think can be done with computer science that isn't just moving around huge amounts of data very fast. These ideas that use computer science to directly impact people's lives don't have to be exceptionally hard to implement either, they just need more people to think about them. It's part of why I've chosen to work here at a non-profit, over some big company. :smile: 

3. Going along with the previous point, I do want to encourage different types of people to consider computer science. I think that computer science in general has a bit of a branding problem, as I think a lot of students have written it off for only websites, games or apps, and that it's extremely complicated. At least... that was my experience in school! :joy: When I would talk to peers about it, and tell them what I actually do, they seemed to realize how different it was compared to their perceptions about it, and they definitely were more interested in it, and finding out a bit more.

I'll drop the idea of "computer science for the greater good" as the core, since I don't want to make the curriculum only about social justice topics. However, I do want to introduce it as a theme, as I think it might intrigue people more who have never been exposed to it. I think that these clubs will always attract those who are already interested by computer science, but I want to combine those people with some base knowledge of these concepts with people who have never thought about it, but want to do interesting things, and see what comes out of that partnership. I think that by having diverse opinions and backgrounds within a group of people, you can create something truly amazing. This is something that companies are (finally) starting to realize, and it's something I'd love to introduce to students early.

**Comment by remixz** [comment]
Closing in favour of GH-751 and GH-752.
