### ISSUE TITLE
Investigate replacing Twilio workshop

### ISSUE THREAD

**Issue by remixz** [hackclub/hackclub#746]
Although the Twilio workshop is fun, there are issues with its setup.

* Twilio requires a credit card, even when applying credit. Unfortunately, when we provide a credit card to use, it looks like when it's used too much, it starts to be denied.
* Our Twilio library assumes the club is in the US, and will provision a US number. This may incur long distance texting charges for people outside of the US.

As well, this workshop may not be as accessible by some clubs, where Twilio may not be supported in their region, or just that a student doesn't have a cell phone to use.

So... investigation time! I'll be thinking of ideas of a replacement that involves some of the same concepts, plus still can create something useful, and will put them in this issue. I'd love to hear any suggestions, though. :smile:

**Comment by paked** [comment]
Yes. I remember a specific case when @MaxWofford and I went to a High School to pitch The Hack Series (an event we ran in December) to a group of students. We had a really neat Twilio demo set up, but none of the students were able to partake because they were not allowed to use their phones in school. I'm not quite sure what this would be like for after school clubs though.

**Comment by zachlatta** [comment]
Yeah, I'm totally down for this too. It's such a shame that there's no easier way to get people set up with Twilio – it's easily our most engaging workshop.

Any thoughts for an engaging second workshop that'd introduce JavaScript well?

**Comment by remixz** [comment]
As discussed on the call today (https://www.youtube.com/watch?v=IO-vVJlB9a0), I'm going to work on a workshop that uses https://wit.ai, a natural language processing API to replace Twilio. I plan to have a first draft by Monday, which I'll post here.

**Comment by zachlatta** [comment]
:ok_hand:

On Thu, Mar 3, 2016 at 3:31 PM, Zach Bruggeman <notifications@github.com>
wrote:

> As discussed on the call today (
> https://www.youtube.com/watch?v=IO-vVJlB9a0), I'm going to work on a
> workshop that uses https://wit.ai, a natural language processing API to
> replace Twilio. I plan to have a first draft by Monday, which I'll post
> here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/746#issuecomment-192019741>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by remixz** [comment]
Thoughts (will be editing this comment a lot as I have things I want to remember/document):

* The wit.ai interface is kind of confusing to add new entites and intents. However, they offer a "fork" option on projects, so I think for the workshop, we'll offer a project with a bunch of intents set up that people can fork, and then if they want to go deeper, they can add intents/entities to that project.
* The API doesn't support CORS (:unamused:), but does support JSONP. (:unamused: :unamused: :unamused:) With the library we'll be making, since wit.ai doesn't have a JS library for text input, I guess JSONP will work fine. We can use jQuery's approach to JSONP, where it'll take the callback, temporarily assign it as a global variable, and then once it's called, it'll remove it from the global scope. Alternatively, if we do feel that we need a proxy due to school filters, then we could add CORS headers to the proxy, and not have to do that.

**Comment by zachlatta** [comment]
Just in case the API is significantly easier to use, it's pretty trivial to
set up Surrogate (https://github.com/hackclub/surrogate) to add CORS
headers. There are privacy worries though, since we'd be proxying their
authentication info.

On Thu, Mar 3, 2016 at 5:01 PM, Zach Bruggeman <notifications@github.com>
wrote:

> Thoughts (will be editing this comment a lot as I have things I want to
> remember/document):
>
>    - The wit.ai interface is kind of confusing to add new entites and
>    intents. However, they offer a "fork" option on projects, so I think for
>    the workshop, we'll offer a project with a bunch of intents set up that
>    people can fork, and then if they want to go deeper, they can add
>    intents/entities to that project.
>    - The API doesn't support CORS ([image: :unamused:]), but does support
>    JSONP. ([image: :unamused:] [image: :unamused:] [image: :unamused:])
>    With the library we'll be making, since wit.ai doesn't have a JS
>    library for text input, I guess JSONP will work fine. We can use jQuery's
>    approach to JSONP, where it'll take the callback, temporarily assign it as
>    a global variable, and then once i t's call ed, it'll remove it from the
>    global scope. Alternatively, if we do feel that we need a proxy due to
>    school filters, then we could add CORS headers to the proxy, and not have
>    to do that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/746#issuecomment-192042941>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by ad510** [comment]
I tried to make the Bigfoot workshop beginner friendly, and it only needs the Personal Website workshop as a prerequisite. Any reason that can't be the second workshop?

**Comment by ad510** [comment]
One problem with Bigfoot is it currently isn't obvious how club members might improve on it when the workshop is done. I think that aspect can be improved by making clicking the image link to another page instead of opening an alert. This would let people turn it into a point and click adventure game (without JS!)

**Comment by zachlatta** [comment]
We're implementing our new curriculum plan in #778, which doesn't include the Twilio workshop. As a result, going to go ahead and close this.

**Comment by jajoosam** [comment]
@zachlatta @MaxWofford what do you guys think about creating another twilio workshop - except with WhatsApp bots?

The trial now does not require a credit card, and WhatsApp bots would be accessible globally 😄 

I've written a workshop already on this, let me know if you'd be interested in having this as an official workshop 👉  https://dsh.re/8c48f6

**Comment by lachlanjc** [comment]
@jajoosam +1 on everything @MaxWofford said^

**Comment by jajoosam** [comment]
And created! 

https://github.com/hackclub/hackclub/pull/1152 

@MaxWofford @zachlatta @lachlanjc
