### ISSUE TITLE
Hack Club photos

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#749]
Anyone have thoughts on putting more photos of what Hack Clubs look like online?

Here are a couple photos I've taken at a variety of things for Hack Club: https://goo.gl/photos/AKoSbyD9N2WDCMYs7

**Comment by MaxWofford** [comment]
@zachlatta What if the background image changed on hackclub.com?
![screenshot from 2016-03-02 17 47 05](https://cloud.githubusercontent.com/assets/5891442/13478381/cd99e5ce-e09e-11e5-83c7-0a8737e93896.png)

**Comment by zachlatta** [comment]
Not a huge fan of having it change in a carousel or anytime the page loads.
I think having a consistent header is more powerful and presents a more
uniform experience.

On Wed, Mar 2, 2016 at 2:47 PM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> What if the background image
> changed on hackclub.com?
> [image: screenshot from 2016-03-02 17 47 05]
> <https://cloud.githubusercontent.com/assets/5891442/13478381/cd99e5ce-e09e-11e5-83c7-0a8737e93896.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/749#issuecomment-191476988>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
@zrl: Maybe we can replace the rainbow on our website with background images
![screenshot from 2016-03-02 18 15 02](https://cloud.githubusercontent.com/assets/5891442/13479112/c332b45e-e0a2-11e5-9bbd-a971e1ab96bd.png)

**Comment by zachlatta** [comment]
Oooo, I love that idea.

@remixz: you've done more web development than me, what are your thoughts?

On Wed, Mar 2, 2016 at 3:15 PM, Max Wofford <notifications@github.com>
wrote:

> @zrl <https://github.com/zrl>: Maybe we can replace the rainbow on our
> website with background images
> [image: screenshot from 2016-03-02 18 15 02]
> <https://cloud.githubusercontent.com/assets/5891442/13479112/c332b45e-e0a2-11e5-9bbd-a971e1ab96bd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/749#issuecomment-191488357>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by remixz** [comment]
As long as make sure the text above is still readable, I think it'd look good. We should probably make them all a fixed height, so we have a consistent area of picture shown in the sections.

**Comment by MaxWofford** [comment]
We could close this and https://github.com/hackclub/website/issues/206 with something like:

![screenshot from 2016-03-04 10 14 03](https://cloud.githubusercontent.com/assets/5891442/13530959/ef7f876c-e1f1-11e5-9ff6-553e96f7c54a.png)

**Comment by zachlatta** [comment]
Hmm, it feels a little out of place there. What are your thoughts @remixz?

On Fri, Mar 4, 2016 at 7:15 AM, Max Wofford <notifications@github.com>
wrote:

> We could close this and hackclub/website#206
> <https://github.com/hackclub/website/issues/206> with something like:
>
> [image: screenshot from 2016-03-04 10 14 03]
> <https://cloud.githubusercontent.com/assets/5891442/13530959/ef7f876c-e1f1-11e5-9ff6-553e96f7c54a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/749#issuecomment-192317516>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Actually, on second thought, I think that layout may make a ton of sense for showing a testimonial. Let's add it to the site.

I'll post a few testimonials we can use in a bit.

**Comment by zachlatta** [comment]
Here's two:

> It is an understatement to say that Hack Club is one of those experiences that impacted my life. There’s a strict, obvious contrast with high school: a place full of judgment, an environment that devalues creative freedom, an atmosphere so lonely with constant glorification of useless issues. It is such a wonderful thing to know a place so different from that exists.

\- Anonymous

> This is my club's first year and it's been leaps and bounds better than expected. Over the course of the year our more than 80 members have made games and websites, participated in hackathons, and have volunteered at a local middle school for their hour of code. I started my club after talking to Hack Club and can say it wouldn't be a reality if they weren't around.

\- Raphael Kats
