### ISSUE TITLE
Posters

### ISSUE THREAD

**Issue by jkwok91** [hackclub/hackclub#750]
_From @jkwok91 on March 2, 2016 22:25_

Opening this issue to keep track of poster templates I'll be creating for anyone who needs some inspiration for their clubs. These are primarily for (hopefully) inspiration, and are all open to club use and remixing, but keep in mind that they all require customization.

Requirements for posters:
- an attention-catching hook (usually referring to what the meeting will be about)
- name of club (for my templates, I will be using "Hack Club" as the club name, which you should replace with your club's name. Unless your club's name is "Hack Club.")
- date, time, and place of club meeting

_Copied from original issue: hackclub/meta#505_

**Comment by jkwok91** [comment]
Sorry for the accidental assign @JevinSidhu!

**Comment by jkwok91** [comment]
![plain__learn_to_create_personal_site](https://cloud.githubusercontent.com/assets/2666337/13480609/bf2f8fa8-e093-11e5-8fc0-f8e62991709c.png)

Notes on this:
- states the three main things (purpose of meeting, name of club, date/time/place of meeting)
- also mentions that it's the first meeting. I wanted to include this because in my personal experience it has been easier to attend a first meeting than join a club in a subsequent meeting. Of course that's not to say you shouldn't join a club in a subsequent meeting!
- kept it simple with Helvetica, and only three variations: Regular [large], regular [small], and bold [small].
- played with the alignment to create a diagonal and thus a direction for the eye. (The user will read starting with hook, ending with logistics.)

**Comment by MaxWofford** [comment]
@jkwok91 Might be cool to get the ajar.io poster officially documented.

**Comment by jkwok91** [comment]
@MaxWofford yep, talked to @zachlatta about having a repo for all clubs to upload their posters to inspire other clubs / collaborate.

**Comment by zachlatta** [comment]
What if we just put them in the `clubs` directory in this repo? Could have
a `posters` folder.

I'm thinking that directory would be a good place for everything clubs,
except curriculum.

On Wed, Mar 2, 2016 at 5:17 PM, JESSICA <notifications@github.com> wrote:

> @MaxWofford <https://github.com/MaxWofford> yep, talked to @zachlatta
> <https://github.com/zachlatta> about having a repo for all clubs to
> upload their posters to inspire other clubs / collaborate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/750#issuecomment-191524452>.
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
![screen shot 2016-03-02 at 11 38 37 pm](https://cloud.githubusercontent.com/assets/2666337/13501902/5512fa94-e11d-11e5-8a32-01fb224a4f84.png)
Notes:
- a somewhat more humorous take, with the poster centered around a graphic

![screen shot 2016-03-03 at 8 54 09 am](https://cloud.githubusercontent.com/assets/2666337/13501946/8b745aba-e11d-11e5-9832-1a17947dd53b.png)
Notes:
- took some inspiration from old film posters
- hand lettering to get the vibe I wanted
- words at an angle for movement
