### ISSUE TITLE
Create official documentation of tiered workshop system

### ISSUE THREAD

**Issue by remixz** [hackclub/hackclub#751]
Discussed in call: https://www.youtube.com/watch?v=IO-vVJlB9a0

Overview of system:

* **Hack Club: Sandbox**
  * All workshops (including staff-made) start in the sandbox
  * Will have lots of workshop ideas and unfinished content
  * Encourages community to experiment with ideas and propose what they're passionate about
  * Ideas can be picked up by other people across clubs to work on

* **Hack Club: Curriculum**
  * Finished workshops, certain level of quality
  * Some may be staff-made, some may be made by community
  * Fit into "playlists", where we'll give clubs options of content depending on what members are interested in working on
  * "Initial" playlist will be content that all members do, to expose them to a bunch of different ideas and fields
  * Maintained by staff, in terms that we'll ensure all workshops, including community-made, do work, and will provide support
  * Incentivizes community members to contribute workshops, since it'll have a lasting impact on their local community, and on communities around the world

**Comment by zachlatta** [comment]
:+1:

On Thu, Mar 3, 2016 at 3:12 PM, Zach Bruggeman <notifications@github.com>
wrote:

> Discussed in call: https://www.youtube.com/watch?v=IO-vVJlB9a0
>
> Overview of system:
>
>    -
>
>    *Hack Club: Sandbox*
>    - All workshops (including staff-made) start in the sandbox
>       - Will have lots of workshop ideas and unfinished content
>       - Encourages community to experiment with ideas and propose what
>       they're passionate about
>       - Ideas can be picked up by other people across clubs to work on
>    -
>
>    *Hack Club: Curriculum*
>    - Finished workshops, certain level of quality
>       - Some may be staff-made, some may be made by community
>       - Fit into "playlists", where we'll give clubs options of content
>       depending on what members are interested in working on
>       - "Initial" playlist will be content that all members do, to expose
>       them to a bunch of different ideas and fields
>       - Maintained by staff, in terms that we'll ensure all workshops,
>       including community-made, do work, and will provide support
>       - Incentivizes community members to contribute workshops, since
>       it'll have a lasting impact on their local community, and on communities
>       around the world
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/751>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by jkwok91** [comment]
Now my question is, where do I stick this?

**Comment by MaxWofford** [comment]
@jkwok91 If you want to record it as notes, hackclub/meta. If you want to record it as official documentation, somewhere in hackclub/hackclub.

**Comment by zachlatta** [comment]
I think this probably deserves a spot in the main CONTRIBUTING.md or in
workshops/CONTRIBUTING.md. Maybe even in workshops/README.md.

On Thu, Mar 31, 2016 at 10:02 AM, Max Wofford <notifications@github.com>
wrote:

> @jkwok91 <https://github.com/jkwok91> If you want to record it as notes,
> hackclub/meta. If you want to record it as official documentation,
> somewhere in hackclub/hackclub.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/751#issuecomment-204022653>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
