### ISSUE TITLE
Document our curricular direction 

### ISSUE THREAD

**Issue by remixz** [hackclub/hackclub#752]
Discussed in call: https://www.youtube.com/watch?v=IO-vVJlB9a0

Our general direction for new content going forward is to create content that engages multiple types of personalities. We want to do this by showing how computer science can be used in ways that aren't typically exposed by tutorials, especially for newcomers. Some examples might be through music, English, cryptography (CTF!), etc. 

We're not against more "traditional" creations seen in tutorials, like websites and games, but since there's already so much of this content out there, we want to focus on creating engaging content that doesn't already exist in a new-programmer friendly way. We'll be curating content we feel is exceptional in its teaching of these creations for new programmers. As well, our community can contribute workshops for these things as they're interested. (See GH-751)

Our overall goal is to create a very creative space in these clubs, and with that, students aren't just learning about computer science fundamentals, but also learning about ways they can be creative with it, and how they can interact with others while doing so. We also want to entice people who aren't already interested in computer science, and may not think about how it can be used aside from websites or games.

**Comment by MaxWofford** [comment]
@remixz Where will this and #751 be documented?

**Comment by zachlatta** [comment]
Closed by hackclub/meta#517 (see https://github.com/hackclub/meta#curriculum-plan). Does this address your comment @MaxWofford?

**Comment by MaxWofford** [comment]
Yep!
