### ISSUE TITLE
Add instructions on how to shallow clone this repository

### ISSUE THREAD

**Issue by remixz** [hackclub/hackclub#753]
This was mentioned in our call today. (https://www.youtube.com/watch?v=IO-vVJlB9a0) Because the repository is a bit large, we want to create instructions on how to do a shallow clone of this repository, so they don't have the history of old files.

I'm going to leave this open to anyone, as it'd be an easy contribution, and a good first contribution for someone in the community who wants to start contributing to our curriculum. However, if nobody really wants to do this, I can.

**Comment by MaxWofford** [comment]
@remixz As you mentioned, this can be done as a first contribution. I just added the first-timers only tag.

**Comment by kazekagegaara** [comment]
@remixz @MaxWofford are you looking for something like this - `git clone --depth 1 https://github.com/hackclub/hackclub.git` ? Where should this be added?

**Comment by MaxWofford** [comment]
@kazekagegaara Yep! We want to add it somewhere new contributors will see it. Probably in `CONTRIBUTING.md` and `README.md`.

**Comment by remixz** [comment]
Fixed with GH-754.
