### ISSUE TITLE
Remove part 2 of Soccer

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#768]
I don't think there's ever going to be a part 2 of Soccer built because we're starting to flesh out our new curriculum plan now.

https://github.com/hackclub/hackclub/tree/master/workshops/soccer#part-2-adding-more-functionality

/cc @JSneak @jkwok91

**Comment by jkwok91** [comment]
What kind of additional functionality was planned?

**Comment by zachlatta** [comment]
Honestly, no idea. I think Jonathan had some ideas, but I got the
impression that there wasn't anything very concrete.

On Sat, Apr 2, 2016 at 1:49 PM, JESSICA <notifications@github.com> wrote:

> What kind of additional functionality was planned?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/768#issuecomment-204803051>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
