### ISSUE TITLE
Implement New Curriculum Plan

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#778]
This issue is to track the implementation of our new [curriculum plan](https://github.com/hackclub/meta#curriculum-plan). We'll be regularly updating this issue with progress.

(Note: `#` represents the meeting number)

|   # | Topic                           | Status                                                                    | Link                     |
| --- | ------------------------------- | ------------------------------------------------------------------------- | ------------------------ |
|   1 | Introduction & Personal Website | Workshop created, introduction needs to be fleshed out                    | [Here][personal_website] |
|   2 | Coding is...                    | That Was Easy Workshop                                                       | [Here][that_was_easy]       |
|   3 | Coding is...                    | Geometric Patterns in p5.js                                         | [Here] [geometric_pattern]                     |
|   4 | Deep Dive 1 - Game Development  | Dodge Workshop                                                            | [Here][dodge]            |
|   5 | Deep Dive 1 (cont.)             | Platformer                                                                     | [Here][platformer]                      |
|   6 | First Hack Day                  | No content on running this has been put together yet                      | N/A                      |
|   7 | First Demos                     | No content on running this has been put together yet                      | N/A                      |
|   8 | Deep Dive 2                     | Notes stored in local storage                              | [Here][notes_to_self]                      |
|   9 | Deep Dive 2 (cont.)             | Firebase chat                              | [Here][chat]                      |
|  10 | Deep Dive 2 (cont.)             | Collab Sketch with Firebase                          | [Here][collab_sketch]                      |
|  11 | Second Hack Day                 | No content on running this has been put together yet                      | N/A                      |
|  12 | Second Hack Day Demos           | Not content on running this has been put together yet                     | N/A                      |
|  13 | Electives                       | Maybe something with three.js                                                           | N/A                      |
|  14 | Electives                       | No content yet                                                            | N/A                      |
|  15 | Electives                       | No content Yet                                                            | N/A                      |

[personal_website]: https://workshops.hackclub.com/personal_website
[that_was_easy]: https://workshops.hackclub.com/that_was_easy
[geometric_pattern]: https://workshops.hackclub.com/geometric_pattern
[dodge]: https://workshops.hackclub.com/dodge
[platformer]: https://workshops.hackclub.com/platformer/
[notes_to_self]: https://workshops.hackclub.com/notes_to_self/
[chat]: https://workshops.hackclub.com/chat/
[collab_sketch]: https://workshops.hackclub.com/collaborative_sketch

Updated 1 May 2016:
### Week: May 2-8
  - [x] Finish Soundboard workshop
  - [x] Write first draft of Geometric Pattern workshop with p5.js
    - [x] Test with Julia on Sunday
    - [x] Test with rest of user-testing group
  - [x] Come up with ideas for electives, possibly using an API
    - Quizzes with Firebase

### Week: May 9-15
  - [x] Come up with idea for developing Dodge for Deep Dive 1.
  - [x] ~~FInish Soundboard workshop~~ Simplify it
    - [x] Make demo
    - [x] ~~Make extended demo~~ Soundboard is the extended demo, ha
  - [x] Finish Geometric Pattern workshop
    - [x] Make demo
    - [x] Make extended demo
  - [x] Edit Dodge workshop
  - [x] Write first draft of the second workshop for Deep Dive 1, making sure it goes well with the first part (Dodge)
    - [x] Test with user-testing group
  - [x] Come up with Deep Dive 2 or elective ideas (most likely there will be some swapping), taking into account the level at which our user-testing users are doing
    - [x] ~~Build todo list / some list variant~~ Firebase stuff!

### Week: May 16-22
  - [x] Finish deepdive 1
  - [x] Write draft of Deep Dive 2 (that's three drafts)
    - [x] DD 2.1
    - [x] DD 2.2
    - [x] DD 2.3
    - [x] Test with user-testing group
  - [x] Generate more elective ideas and start building some to see how it feels

### Week: May 23-29
  - [x] Simplify soundboard (hackclub/hackclub#833)
  - [ ] Create while-loop gifs
  - [ ] Create for-loop gifs
  - [ ] Create array gifs
  - [x] Finish drafts of Deep Dive 2
    - [x] Continue testing Deep Dive 2
  - [x] Begin tentative drafts of electives (at least 1)

### Partial Week: May 30 - June 3
  - [x] Finalize all completed drafts (everything up to and including deep dive 2)
  - [ ] Flesh out electives slightly more
  - [ ] Continue testing across all workshops

**Comment by MaxWofford** [comment]
Let's close #695 once this is closed

**Comment by zachlatta** [comment]
:ok_hand:

On Thu, Apr 7, 2016 at 9:06 AM, Max Wofford <notifications@github.com>
wrote:

> Let's close #695 <https://github.com/hackclub/hackclub/issues/695> once
> this is closed
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/778#issuecomment-206971682>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
@zachlatta @jkwok91 Where can I find out more about the elective workshops? Are they created by the core team, or community?

**Comment by zachlatta** [comment]
@MaxWofford sorry for not getting back to this sooner. Elective workshops = all of the above. Basically any workshops that aren't part of the core track, whether created by community or staff.

**Comment by zachlatta** [comment]
Went ahead and assigned you to this because you're basically taking point on it right now, @jkwok91. Let me know if you'd prefer me to reassign myself.

**Comment by zachlatta** [comment]
@jkwok91 can you update this issue with where we're at today and what needs to happen next?

**Comment by zachlatta** [comment]
I'll take point on updating this and making sure it gets closed.

**Comment by zachlatta** [comment]
It seems like all of the work for this has been done, but the issue simply hasn't been updated. This issue can be closed once it's updated to reflect reality.

**Comment by zachlatta** [comment]
Going to just go ahead and close this.
