### ISSUE TITLE
Create first "Coding is..." workshop

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#779]
Create a workshop that meets the criteria outlined in https://github.com/hackclub/meta#meetings-2-3---coding-is. This can either be a completely new workshop or we can modify existing content. This is for the second meeting in #778.

This'll be the club member's first introduction to "real coding". Our goal is to show them that coding is about a lot more than building apps, websites, and games. I also think this means we should stray away from using tools like Twine because the user doesn't write real code when using them.

A few ideas for what this could be:

- Text adventure game (built using HTML & CSS, not Twine)
- Make music using code
- Twilio (this is a great introduction to the power of code, but unfortunately very difficult to implement because Twilio has a habit of banning us)

**Comment by jkwok91** [comment]
Text adventure using HTML & CSS is boring and repetitive and horrible. I've done it and I've written the workshop and it is horrible and uninspired.

**Comment by zachlatta** [comment]
Want to submit the workshop as a sandbox workshop? May be worth just having
around in the repo, even if it's not ready for meetings.

On Mon, Apr 11, 2016 at 10:48 PM, JESSICA <notifications@github.com> wrote:

> Text adventure using HTML & CSS is boring and repetitive and horrible.
> I've done it and I've written the workshop and it is horrible and
> uninspired.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/779#issuecomment-208717969>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
What if we go ahead with #784 for this one?

**Comment by jkwok91** [comment]
Yea, but there are two "Coding is..." workshops

**Comment by zachlatta** [comment]
Yeah, but this issue is just to track the first one.

On Tue, Apr 12, 2016 at 1:44 PM, JESSICA <notifications@github.com> wrote:

> Yea, but there are two "Coding is..." workshops
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/779#issuecomment-209094892>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
Aha, I thought "first" meant "first in order of curriculum." Ok, got it.

**Comment by jkwok91** [comment]
Closing because Soundboard workshop is in the repo
