### ISSUE TITLE
Add GitHub's third signup step to Personal Website

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#798]
GitHub added a new screen when creating an account, shown below:

![tmp](https://cloud.githubusercontent.com/assets/992248/14764843/024e87ec-097c-11e6-8384-2f0d2d8975fe.png)

We need to clarify that they should just click "skip this step" when they get to this page.

**Comment by jkwok91** [comment]
Do we need this? I have a gif ready, but since we changed the wording; it doesn't seem like a huge issue.

**Comment by zachlatta** [comment]
A bunch of people got stuck on it during the Saturday workshop, but my
sister seemed fine when she ran it yesterday.

I'll leave this up to you. If you decide we don't want to do this, just go
ahead and close the issue.

On Tue, Apr 26, 2016 at 8:13 AM, JESSICA <notifications@github.com> wrote:

> Do we need this? I have a gif ready, but since we changed the wording; it
> doesn't seem like a huge issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/798#issuecomment-214778627>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by jkwok91** [comment]
Let's decide after Thursday's event.

**Comment by zachlatta** [comment]
:ok_hand:

On Wed, Apr 27, 2016 at 8:33 AM, JESSICA <notifications@github.com> wrote:

> Let's decide after Thursday's event.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/798#issuecomment-215122382>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by zachlatta** [comment]
Turned out to be a complete non-issue during today's event. I think our other revisions to the sign-up process ended up solving the part where people got stuck on this.
