### ISSUE TITLE
Make it clear that the user shouldn't do GitHub's tutorial in Personal Website

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#799]
We ran a workshop in Berkeley today and a ton of participants got stuck when they accidentally clicked GitHub's "Hello World" tutorial.

When you create a new GitHub account, you're shown the following page and it's very tempting to click "Let's get started!", which brings you to https://guides.github.com/activities/hello-world/.

![tmp](https://cloud.githubusercontent.com/assets/992248/14764846/18730886-097c-11e6-8c67-6e987de19a75.png)

We need to make sure members don't accidentally click this – I'd say one in four people did during the workshop and got totally thrown off.

**Comment by MaxWofford** [comment]
This was closed by #803

/cc @jkwok91 @zachlatta
