### ISSUE TITLE
Create Bootstrap workshop

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#807]
@jkwok91 and I were talking about creating a workshop on Bootstrap as our second workshop instead of Soundboard. It'd go Personal Website -> Bootstrap -> Soundboard -> Dodge. We're not super set on this yet, but we think it's worth experimenting with.

This issue is to track the creation of that workshop. I'll comment on here with a basic draft at some point tomorrow.

**Comment by jkwok91** [comment]
This was a failure. Closing now.
