### ISSUE TITLE
Twilio - GIF Background not changing background on text. 

### ISSUE THREAD

**Issue by AbelRR** [hackclub/hackclub#812]
Step by step, 

1. Open https://workshops.hackclub.com/twilio
2. Scroll down to**Examples**
3. Open GIF Background (advanced) 
4. Replace and input SID & TOKEN
5. Click button in output "Run with JS"
6. My Number appears in console
7. I text my twilio number : robots
then I try: "robots" 
8. Nothing seems to happen after this. 

Maybe I was not supposed to run it  on JSBIN: http://jsbin.com/gist/fbc17a8a8f43a7b9e5ea?html,js,console,output. I also tried inputting the code in Cloud 9, and same results.

**Comment by zachlatta** [comment]
Awesome, thanks so much for catching this and filing the bug report. I just fixed this – all should be working now.

Turns out that an old version of [surrogate](https://github.com/hackclub/surrogate) was deployed and it didn't have the latest Giphy proxy. I've since redeployed.
