### ISSUE TITLE
Improve Soundboard to inspire more exploration 

### ISSUE THREAD

**Issue by jkwok91** [hackclub/hackclub#833]
Currently, Soundboard walks the user through how to place a button on their HTML page, and then connect an event handler so that when the button is clicked, a sound will be played. Then it tells the user to repeat this 15 times.

What I'm proposing is that we replace the 15 repetitions with some styling (perhaps make the button attractive and red, like the Staples "Easy" button), and let the user come up with their own ideas for how they can use this new knowledge. We'll have to flesh out the Hacking section to encourage this.

Sample hacking ideas:
- make the big red button play different sounds
- make the big red button open email client
- make the big red button close the tab
- make three different buttons, only one of which will do something (sort of like a guessing game?)

I'll build the demos for each of these hacking ideas and put screenshots in the hacking section.

**Comment by jkwok91** [comment]
Oh I just realized that we'll have to rename this workshop.

**Comment by jkwok91** [comment]
The tentative title is `sound_button`. As you can see, I do not have a knack for appealing names.

**Comment by jkwok91** [comment]
Is it too condescending to divide up the Hacking section into "things you learned"? Example:

Sounds
- change the sound played by the button

Buttons
- create more buttons

Event Handling with Click
- write function to close tab on click
- change bg color on click

Triggering Click with code
- ...

Okay actually I'm gonna answer my own question and say that I don't want to do this because 1) it's hard to break it up into categories cuz there's a lot of overlap and 2) what is the point of this.
Leaving this comment for posterity.

**Comment by zachlatta** [comment]
What if we called it "The Button" or "Don't Click The Button"?

**Comment by jkwok91** [comment]
I found [this](http://mhwalkers.freevar.com/sounds/that_was_easy.wav) and I'm going to use it until we get sued by Staples.

**Comment by jkwok91** [comment]
New tentative title is `That Was Easy`

**Comment by zachlatta** [comment]
I love it.

On Mon, May 23, 2016 at 7:02 PM, JESSICA <notifications@github.com> wrote:

> New tentative title is That Was Easy
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/833#issuecomment-221146974>
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>
