### ISSUE TITLE
Rename collab_sketch -> collaborative_sketch

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#845]

**Comment by MaxWofford** [comment]
On second thought, let's name it collab_sketch. We're already calling it that in most locations.

**Comment by MaxWofford** [comment]
@zachlatta told me in person hackers were confused by "collab sketch"

**Comment by zachlatta** [comment]
:+1:

**Comment by MaxWofford** [comment]
Closed by https://github.com/hackclub/hackclub/pull/866
