### ISSUE TITLE
Notes to Self workshop doesn't show local storage for Firefox

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#851]
Hackers going through this workshop in Firefox were confused.

**Comment by MaxWofford** [comment]
We've stopped running this workshop at Hack Camp. I'm going to deprecate this workshop. Closing this issue.

**Comment by zachlatta** [comment]
Wait, err – did you mean to say that you're going to close this? You also just submitted #882.

**Comment by zachlatta** [comment]
Actually, I'll just go ahead and close because I merged #882.
