### ISSUE TITLE
collab_sketch doesn't delete on other tabs until refreshed

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#853]
This can be fixed with something like this:

```js
  pointsData.on('child_removed', function () {
    points = []
  })
```

**Comment by zachlatta** [comment]
What do you mean by "delete on other tabs until refreshed"?

**Comment by jkwok91** [comment]
Probably like, no live update/syncing? upon clearing canvas?

2016-06-15 14:39 GMT-07:00 Zach Latta <notifications@github.com>:

**Comment by ssun098** [comment]
Yeah, what @jkwok91 said. Confirmed @MaxWofford's code works though

**Comment by MaxWofford** [comment]
Closed by https://github.com/hackclub/hackclub/commit/b353becc3a261998d1232352814829caa9e6f01f
