### ISSUE TITLE
Add explanation of JS object property to collab_sketch

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#857]
While running collab_sketch I had to explain how object properties worked to each of the hackers. It'd be cool if we covered this in the workshop.

**Comment by zachlatta** [comment]
@xizhao has volunteered to take a stab at this issue. Apologies for all the assignment back and forth.

**Comment by xizhao** [comment]
PR submitted

**Comment by xizhao** [comment]
updated.

**Comment by zachlatta** [comment]
:raised_hands:

On Fri, Jul 8, 2016 at 11:09 PM, xizhao <notifications@github.com> wrote:

> updated.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/hackclub/issues/857#issuecomment-231517974>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA8j-GaY3eVlms17NYU7WlteiEU7hNgpks5qTzszgaJpZM4I2_jY>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by MaxWofford** [comment]
Closed by #869
