### ISSUE TITLE
Create images of HTML and CSS syntax for personal_website workshop

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#863]
For example:   
![](https://s3.amazonaws.com/codecademy-content/courses/ltp/img/2/a.png)  
![](https://s3.amazonaws.com/codecademy-content/courses/ltp/img/2/p.png)

**Comment by zachlatta** [comment]
Unassigned because @jkwok91 is no longer taking point on curriculum.

**Comment by MaxWofford** [comment]
Closing this because it's not worth the time right now.
