### ISSUE TITLE
Document requirement of metadata.yml in workshops/CONTRIBUTING.md

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#906]
Now that #904 is merged, we need to document in `workshops/CONTRIBUTING.md` that every new workshop must have a `metadata.yml` file in it with the correct schema.

Can you take this @ssun098?

**Comment by ssun098** [comment]
Yep, would be happy to take it

**Comment by ssun098** [comment]
Closed by https://github.com/hackclub/hackclub/pull/907
