### ISSUE TITLE
Move iOS workshop to Core Workshops

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#909]
@jkwok91 has tested @zach-cmiel's iOS workshop successfully, I say we move it to the "Core Workshops" section in `workshops/README.md`.

**Comment by paked** [comment]
On it!

**Comment by paked** [comment]
Closed by #914

**Comment by MaxWofford** [comment]
![](https://media.giphy.com/media/sWHsgcdrnCIda/giphy.gif)
