### ISSUE TITLE
Renew SSL certificate for *.hackclub.com

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#971]
- [ ] Renew SSL certificate
- [ ] Update all Heroku apps
  - [ ] `api-hackclub`
  - [ ] `lecture-hall`
  - [ ] `website-hackclub`
- [ ] Update all Convox apps
  - _TODO: Insert list of Convos apps here_
- [ ] Update `proxy.servers.hackclub.com`

**Comment by MaxWofford** [comment]
@zachlatta Could you elaborate on why this was closed?

**Comment by zachlatta** [comment]
Ah, thanks for catching my lack of explanation.

Closing this because the SSL certificate has been updated.
