### ISSUE TITLE
Consolidate hackclub/meta and hackclub/hackclub

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#973]
I think it's worth having a discussion around merging `hackclub/meta` into this repository.

Pros:

- Less repos = simpler = better
- Consolidated GitHub issues = less confusion around creating issues

Cons:

- Larger repo size

I don't think having a larger repo size should be that much of a concern – we're not going to have too many people cloning this thing and having long-term history is definitely a benefit we want to keep.

Thoughts?

/cc @hackclub/staff

**Comment by paked** [comment]
I don't have much of a strong opinion here, but my gut says to continue with the current model under the name of separation of concerns.

**Comment by MaxWofford** [comment]
Looks like this is completed.
