### ISSUE TITLE
Feedback on the personal website workshop

### ISSUE THREAD

**Issue by lachlanjc** [hackclub/hackclub#982]
Hey all! Ran my first Hack Club meeting today with the personal website workshop. Some feedback based on my experience:

1. Please, tell people to save the files. 😀 I helped 5 different people who had blank sites because they were committing without saving the files first, so nothing went live.
2. C9 seems to have some bugs with its in-app browser, duplicating elements and not applying css. Sometimes clicking the reload button is all the fix needed. Maybe open the external viewer instead and use the save+reload workflow?
3. Introduce the idea of the command line a _bit_ more. It seems simple and natural to us, but it's a totally foreign way to interact with a computer for most. People followed the instructions successfully, but didn't really know what they were dealing with. Perhaps that doesn't matter, but wanted to mention it.
4. Next steps. Encourage people to share their websites with friends/online, and to keep working on them. You could link to useful resources like @nbashaw's sweet [**Dash**](https://dash.generalassemb.ly) project, Codecademy, Mozilla docs, etc, so people can learn how to add links and other rad things.

Overall, it worked super well, so thanks for the awesome docs! None of these are totally necessary, just some suggestions. Great work y'all 💖

**Comment by paked** [comment]
@lachlanjc: Just want to say we haven't forgotten about this issue. It's on my task list and I'm going to get around to addressing your comments super soon :)

Good luck with your next meeting, thank you so much for your feedback ❤️

**Comment by paked** [comment]
Being worked on in #986

**Comment by MaxWofford** [comment]
This is closed by #986
