### ISSUE TITLE
Trouble publishing a website

### ISSUE THREAD

**Issue by Vivek2018** [hackclub/hackclub#983]
So I created a prototype website for our local school hack club, however when it comes to publishing the website in the bash terminal it reads, "Everything up-to-date," however when accessing the code through github the old code is displayed (meaning nothing synced) and when trying to access the website domain through the internet it results in a 404 error.  
![uptodate](https://cloud.githubusercontent.com/assets/25779582/23074495/800f29ac-f4fe-11e6-8ce1-69389fbb13e8.png)
![404](https://cloud.githubusercontent.com/assets/25779582/23074496/800f6a20-f4fe-11e6-81dc-c874811c47a3.png)
![old code](https://cloud.githubusercontent.com/assets/25779582/23074498/8011ca9a-f4fe-11e6-819b-55ce5820fba5.png)
![actual code screen](https://cloud.githubusercontent.com/assets/25779582/23074497/80110380-f4fe-11e6-8af3-a1f7163fc1f0.png)

**Comment by paked** [comment]
I see two problems here.

1. You've named the `index.html` `Index.html`. If you rename the file `index.html` (lowercase 'i'), you should be good. Remember to commit your changes.
2. I don't think you properly committed your changes when updating your website: Remember to run `git add --all`, `git commit -m "Updating website"` before `git push`.

Let me know if this helps!

If you need some more realtime help, ping me on [Slack](https://slack.hackclub.com). I'm `@harrison`.

**Comment by Vivek2018** [comment]
Thank You for your response, after implementing the changes you recommended it seemed that the problem that arrived was with the git commit -m command. Whilst using that command, by typing in "Updating website" after git commit -m it seemed to fix itself. Thanks again.

**Comment by paked** [comment]
Awesome! Glad to have helped.

I'm going to close this issue now, but feel free to open it up (or make another one, if it's not relevant to this issue) in the future!

![https://media.giphy.com/media/897vm5ABNbgFW/giphy.gif](https://media.giphy.com/media/897vm5ABNbgFW/giphy.gif)
