### ISSUE TITLE
Guidelines for club names

### ISSUE THREAD

**Issue by ifvictr** [hackclub/hackclub#984]
Originally from: https://hackclub.slack.com/archives/club-help/p1487371285642120

So basically, there's been a lot of talk about schools disallowing club names (specifically, ones that contain anything related to "hacking"). We need some advice for leaders so they know how to communicate with their schools about the matter.

**Comment by MaxWofford** [comment]
@kyleemile: want to take point on this? I'm happy to work with you on it.

**Comment by paked** [comment]
Hey! This is becoming more and more of a talked about topic on the Slack. I'd really like to have a page we can point people to for when they have this problem.

**Comment by MaxWofford** [comment]
I'll take point on it.

**Comment by JSneak** [comment]
With the addition of the common questions section, I think we can close this issue. The only improvement I can think of is potentially adding a list of alternatives names. 

https://github.com/hackclub/hackclub/tree/master/clubs#what-if-i-cant-call-my-club-hack-club
