### ISSUE TITLE
Consider adding section to club guide on handling members that only come to mess around on computers

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackclub#985]
One issue that a few leaders have mentioned is that there are often members that come to meetings just to mess around on computers.

It might be worth adding a section to the club guide about how to handle this – @ifvictr suggested creating some sort of FAQ or "common pitfalls" section to the guide on handling edge-cases.

Curious to hear everyone's thoughts. 

/cc @hackclub/staff

**Comment by zachlatta** [comment]
Perhaps another thing that could be included in a FAQ: "What if my school doesn't like me calling the club 'Hack Club'?"

**Comment by zachlatta** [comment]
"What if a member of my club does something inappropriate?"

**Comment by zachlatta** [comment]
"What if our adviser does not want to let us meet every week?"

**Comment by zachlatta** [comment]
(all of these are things that have been sent to me)

**Comment by ifvictr** [comment]
I'm graduating this year. How do I transition leadership roles to another person?

**Comment by ifvictr** [comment]
I've secured a teacher adviser/sponsor, but they have no computers. What do we do?

**Comment by JSneak** [comment]
With the inclusion of #1027 , I believe that we can close this issue.

**Comment by paked** [comment]
I don't think we can:

This issue is more about people who come to a Hack Club and play Agar.io (wow so 2015 harrison) instead of learning to program and going through Hack Club's resources.

#1027 addresses what to do if a club member breaks our Code of Conduct, as far as I'm aware not participating is not an infraction on the CoC (and nor should it be, imo).

**Comment by JSneak** [comment]
My bad, totally agree with you. I'll make a new PR to address that aspect.

**Comment by JSneak** [comment]
#1034 Address the final issue.
