### ISSUE TITLE
Tutorial for getting GitHub Student Pack

### ISSUE THREAD

**Issue by ifvictr** [hackclub/hackclub#992]
Just something I didn't seem to see anywhere. I think it'd be nice for all Hack Club members to get their student packs.

**Comment by cravend** [comment]
I've actually started writing a guide for my school's club! The link is [https://github.com/Mason-Development/mason-meta/blob/master/resources/education.md](https://github.com/Mason-Development/mason-meta/blob/master/resources/education.md). I haven't done a whole lot with the resources, so my summaries are pretty basic, but it's still a start!

**Comment by paked** [comment]
@cravend: would you be interested in having this guide made an official Hack Club resource?

**Comment by cravend** [comment]
@paked sure! That'd get a more complete description of what GitHub Education offers. Feel free to incorporate whatever you'd like!

**Comment by AppIns** [comment]
I tried applying and I must have just not been accepted. You should also tell people Bitbucket has private repository support.

**Comment by paked** [comment]
@AppIns: I'd follow up with them. GitHub Education doesn't really reject students.

**Comment by ifvictr** [comment]
@AppIns GitLab also offers free unlimited private repos.

**Comment by MaxWofford** [comment]
Closing this because GitHub's flow for getting the pack as a high school student is much easier now.

![githubpack](https://user-images.githubusercontent.com/5891442/27814104-2902e616-602f-11e7-8b2a-e462a7125c46.PNG)
